## NYC Property Price Prediction

Given *data about property in New York City*, let's try to predict the **price** of a given piece of property.

We will use XGBoost to make our predictions.

Data source: https://www.kaggle.com/datasets/new-york-city/nyc-property-sales

### Importing LIbraries

In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import xgboost as xgb
from sklearn.metrics import r2_score

pd.set_option('display.max_columns', None)

In [2]:
data = pd.read_csv('archive/nyc-rolling-sales.csv')
data

,Unnamed: 0,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,APARTMENT NUMBER,ZIP CODE,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
0,4,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,392,6,,C2,153 AVENUE B,,10009,5,0,5,1633,6440,1900,2,C2,6625000,2017-07-19 00:00:00
1,5,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,399,26,,C7,234 EAST 4TH STREET,,10009,28,3,31,4616,18690,1900,2,C7,-,2016-12-14 00:00:00
2,6,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,399,39,,C7,197 EAST 3RD STREET,,10009,16,1,17,2212,7803,1900,2,C7,-,2016-12-09 00:00:00
3,7,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,402,21,,C4,154 EAST 7TH STREET,,10009,10,0,10,2272,6794,1913,2,C4,3936272,2016-09-23 00:00:00
4,8,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,404,55,,C2,301 EAST 10TH STREET,,10009,6,0,6,2369,4615,1900,2,C2,8000000,2016-11-17 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84543,8409,5,WOODROW,02 TWO FAMILY DWELLINGS,1,7349,34,,B9,37 QUAIL LANE,,10309,2,0,2,2400,2575,1998,1,B9,450000,2016-11-28 00:00:00
84544,8410,5,WOODROW,02 TWO FAMILY DWELLINGS,1,7349,78,,B9,32 PHEASANT LANE,,10309,2,0,2,2498,2377,1998,1,B9,550000,2017-04-21 00:00:00
84545,8411,5,WOODROW,02 TWO FAMILY DWELLINGS,1,7351,60,,B2,49 PITNEY AVENUE,,10309,2,0,2,4000,1496,1925,1,B2,460000,2017-07-05 00:00:00
84546,8412,5,WOODROW,22 STORE BUILDINGS,4,7100,28,,K6,2730 ARTHUR KILL ROAD,,10309,0,7,7,208033,64117,2001,4,K6,11693337,2016-12-21 00:00:00
84547,8413,5,WOODROW,35 INDOOR PUBLIC AND CULTURAL FACILITIES,4,7105,679,,P9,155 CLAY PIT ROAD,,10309,0,1,1,10796,2400,2006,4,P9,69300,2016-10-27 00:00:00

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 84548 entries, 0 to 84547
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Unnamed: 0                      84548 non-null  int64
 1   BOROUGH                         84548 non-null  int64
 2   NEIGHBORHOOD                    84548 non-null  str
 3   BUILDING CLASS CATEGORY         84548 non-null  str
 4   TAX CLASS AT PRESENT            84548 non-null  str
 5   BLOCK                           84548 non-null  int64
 6   LOT                             84548 non-null  int64
 7   EASE-MENT                       84548 non-null  str
 8   BUILDING CLASS AT PRESENT       84548 non-null  str
 9   ADDRESS                         84548 non-null  str
 10  APARTMENT NUMBER                84548 non-null  str
 11  ZIP CODE                        84548 non-null  int64
 12  RESIDENTIAL UNITS               84548 non-null  int64
 13  COMMERCIAL UNITS                84548 non-null  int64
 14  TOTAL UNITS                     84548 non-null  int64
 15  LAND SQUARE FEET                84548 non-null  str
 16  GROSS SQUARE FEET               84548 non-null  str
 17  YEAR BUILT                      84548 non-null  int64
 18  TAX CLASS AT TIME OF SALE       84548 non-null  int64
 19  BUILDING CLASS AT TIME OF SALE  84548 non-null  str
 20  SALE PRICE                      84548 non-null  str
 21  SALE DATE                       84548 non-null  str
dtypes: int64(10), str(12)
memory usage: 14.2 MB

### Preprocessing

In [24]:
data['SALE PRICE'].unique()

array([ 6625000.,  3936272.,  8000000., ...,   408092., 11693337.,
          69300.], shape=(10007,))

In [25]:
data['SALE PRICE'] = data['SALE PRICE'].replace(' -  ', np.nan).astype(float)

In [26]:
# Remove any records where we do not have a sale price
data = data.dropna(axis=0).reset_index(drop=True)

In [27]:
# Split data into X and y
y = data['SALE PRICE'].copy()
X = data.drop('SALE PRICE', axis=1).copy()

In [28]:
y

0         6625000.0
1         3936272.0
2         8000000.0
3         3192840.0
4        16232000.0
            ...
69982      450000.0
69983      550000.0
69984      460000.0
69985    11693337.0
69986       69300.0
Name: SALE PRICE, Length: 69987, dtype: float64

In [29]:
X

,Unnamed: 0,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,APARTMENT NUMBER,ZIP CODE,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE DATE
0,4,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,392,6,,C2,153 AVENUE B,,10009,5,0,5,1633,6440,1900,2,C2,2017-07-19 00:00:00
1,7,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,402,21,,C4,154 EAST 7TH STREET,,10009,10,0,10,2272,6794,1913,2,C4,2016-09-23 00:00:00
2,8,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,404,55,,C2,301 EAST 10TH STREET,,10009,6,0,6,2369,4615,1900,2,C2,2016-11-17 00:00:00
3,10,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,406,32,,C4,210 AVENUE B,,10009,8,0,8,1750,4226,1920,2,C4,2016-09-23 00:00:00
4,13,1,ALPHABET CITY,08 RENTALS - ELEVATOR APARTMENTS,2,387,153,,D9,629 EAST 5TH STREET,,10009,24,0,24,4489,18523,1920,2,D9,2016-11-07 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69982,8409,5,WOODROW,02 TWO FAMILY DWELLINGS,1,7349,34,,B9,37 QUAIL LANE,,10309,2,0,2,2400,2575,1998,1,B9,2016-11-28 00:00:00
69983,8410,5,WOODROW,02 TWO FAMILY DWELLINGS,1,7349,78,,B9,32 PHEASANT LANE,,10309,2,0,2,2498,2377,1998,1,B9,2017-04-21 00:00:00
69984,8411,5,WOODROW,02 TWO FAMILY DWELLINGS,1,7351,60,,B2,49 PITNEY AVENUE,,10309,2,0,2,4000,1496,1925,1,B2,2017-07-05 00:00:00
69985,8412,5,WOODROW,22 STORE BUILDINGS,4,7100,28,,K6,2730 ARTHUR KILL ROAD,,10309,0,7,7,208033,64117,2001,4,K6,2016-12-21 00:00:00
69986,8413,5,WOODROW,35 INDOOR PUBLIC AND CULTURAL FACILITIES,4,7105,679,,P9,155 CLAY PIT ROAD,,10309,0,1,1,10796,2400,2006,4,P9,2016-10-27 00:00:00

In [30]:
# Remove unnecessary/difficult feature columns
{column: len(X[column].unique()) for column in X.select_dtypes('str').columns}

{'NEIGHBORHOOD': 254,
 'BUILDING CLASS CATEGORY': 47,
 'TAX CLASS AT PRESENT': 11,
 'EASE-MENT': 1,
 'BUILDING CLASS AT PRESENT': 161,
 'ADDRESS': 57304,
 'APARTMENT NUMBER': 3320,
 'LAND SQUARE FEET': 5293,
 'GROSS SQUARE FEET': 5095,
 'BUILDING CLASS AT TIME OF SALE': 161,
 'SALE DATE': 362}

In [31]:
len(X['BLOCK'].unique()), len(X['LOT'].unique())

(10848, 2484)

In [32]:
X = X.drop(['Unnamed: 0', 'BLOCK', 'EASE-MENT', 'ADDRESS', 'APARTMENT NUMBER', 'LOT'], axis=1)

In [33]:
X

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BUILDING CLASS AT PRESENT,ZIP CODE,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE DATE
0,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,C2,10009,5,0,5,1633,6440,1900,2,C2,2017-07-19 00:00:00
1,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,C4,10009,10,0,10,2272,6794,1913,2,C4,2016-09-23 00:00:00
2,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,C2,10009,6,0,6,2369,4615,1900,2,C2,2016-11-17 00:00:00
3,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,C4,10009,8,0,8,1750,4226,1920,2,C4,2016-09-23 00:00:00
4,1,ALPHABET CITY,08 RENTALS - ELEVATOR APARTMENTS,2,D9,10009,24,0,24,4489,18523,1920,2,D9,2016-11-07 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69982,5,WOODROW,02 TWO FAMILY DWELLINGS,1,B9,10309,2,0,2,2400,2575,1998,1,B9,2016-11-28 00:00:00
69983,5,WOODROW,02 TWO FAMILY DWELLINGS,1,B9,10309,2,0,2,2498,2377,1998,1,B9,2017-04-21 00:00:00
69984,5,WOODROW,02 TWO FAMILY DWELLINGS,1,B2,10309,2,0,2,4000,1496,1925,1,B2,2017-07-05 00:00:00
69985,5,WOODROW,22 STORE BUILDINGS,4,K6,10309,0,7,7,208033,64117,2001,4,K6,2016-12-21 00:00:00
69986,5,WOODROW,35 INDOOR PUBLIC AND CULTURAL FACILITIES,4,P9,10309,0,1,1,10796,2400,2006,4,P9,2016-10-27 00:00:00

In [34]:
X['LAND SQUARE FEET'] = X['LAND SQUARE FEET'].replace(' -  ', np.nan).astype(float)

In [35]:
X['GROSS SQUARE FEET'] = X['GROSS SQUARE FEET'].replace(' -  ', np.nan).astype(float)

In [36]:
X.isna().mean()

BOROUGH                           0.000000
NEIGHBORHOOD                      0.000000
BUILDING CLASS CATEGORY           0.000000
TAX CLASS AT PRESENT              0.000000
BUILDING CLASS AT PRESENT         0.000000
ZIP CODE                          0.000000
RESIDENTIAL UNITS                 0.000000
COMMERCIAL UNITS                  0.000000
TOTAL UNITS                       0.000000
LAND SQUARE FEET                  0.302742
GROSS SQUARE FEET                 0.310615
YEAR BUILT                        0.000000
TAX CLASS AT TIME OF SALE         0.000000
BUILDING CLASS AT TIME OF SALE    0.000000
SALE DATE                         0.000000
dtype: float64

In [37]:
# Fill missing values with np.nan
for column in ['LAND SQUARE FEET', 'GROSS SQUARE FEET']:
    X[column] = X[column].fillna(X[column].mean())

In [38]:
X.isna().sum().sum()

np.int64(0)

In [39]:
X.dtypes

BOROUGH                             int64
NEIGHBORHOOD                          str
BUILDING CLASS CATEGORY               str
TAX CLASS AT PRESENT                  str
BUILDING CLASS AT PRESENT             str
ZIP CODE                            int64
RESIDENTIAL UNITS                   int64
COMMERCIAL UNITS                    int64
TOTAL UNITS                         int64
LAND SQUARE FEET                  float64
GROSS SQUARE FEET                 float64
YEAR BUILT                          int64
TAX CLASS AT TIME OF SALE           int64
BUILDING CLASS AT TIME OF SALE        str
SALE DATE                             str
dtype: object

In [40]:
# Get year, month and day features from SALE DATE column
X['SALE DATE'] = pd.to_datetime(X['SALE DATE'])

X['YEAR'] = X['SALE DATE'].apply(lambda x: x.year)
X['MONTH'] = X['SALE DATE'].apply(lambda x: x.month)
X['DAY'] = X['SALE DATE'].apply(lambda x: x.day)

X = X.drop('SALE DATE', axis=1)

In [41]:
X

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BUILDING CLASS AT PRESENT,ZIP CODE,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,YEAR,MONTH,DAY
0,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,C2,10009,5,0,5,1633.0,6440.0,1900,2,C2,2017,7,19
1,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,C4,10009,10,0,10,2272.0,6794.0,1913,2,C4,2016,9,23
2,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,C2,10009,6,0,6,2369.0,4615.0,1900,2,C2,2016,11,17
3,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,C4,10009,8,0,8,1750.0,4226.0,1920,2,C4,2016,9,23
4,1,ALPHABET CITY,08 RENTALS - ELEVATOR APARTMENTS,2,D9,10009,24,0,24,4489.0,18523.0,1920,2,D9,2016,11,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69982,5,WOODROW,02 TWO FAMILY DWELLINGS,1,B9,10309,2,0,2,2400.0,2575.0,1998,1,B9,2016,11,28
69983,5,WOODROW,02 TWO FAMILY DWELLINGS,1,B9,10309,2,0,2,2498.0,2377.0,1998,1,B9,2017,4,21
69984,5,WOODROW,02 TWO FAMILY DWELLINGS,1,B2,10309,2,0,2,4000.0,1496.0,1925,1,B2,2017,7,5
69985,5,WOODROW,22 STORE BUILDINGS,4,K6,10309,0,7,7,208033.0,64117.0,2001,4,K6,2016,12,21
69986,5,WOODROW,35 INDOOR PUBLIC AND CULTURAL FACILITIES,4,P9,10309,0,1,1,10796.0,2400.0,2006,4,P9,2016,10,27

In [43]:
# Make numeric categorical features into string columns
for column in ['BOROUGH', 'ZIP CODE']:
    X[column] = X[column].astype(str)

In [44]:
{column: len(X[column].unique()) for column in X.select_dtypes('str').columns}

{'BOROUGH': 5,
 'NEIGHBORHOOD': 254,
 'BUILDING CLASS CATEGORY': 47,
 'TAX CLASS AT PRESENT': 11,
 'BUILDING CLASS AT PRESENT': 161,
 'ZIP CODE': 184,
 'BUILDING CLASS AT TIME OF SALE': 161}

In [45]:
def onehot_encode(df, columns, prefixes):
    df = df.copy()
    for column, prefix in zip(columns, prefixes):
        dummies = pd.get_dummies(df[column], prefix=prefix, dtype=int)
        df = pd.concat([df, dummies], axis=1)
        df = df.drop(column, axis=1)
    return df

In [46]:
# One hot encode remaining nominal columns
nominal_features = ['BOROUGH', 'NEIGHBORHOOD', 'BUILDING CLASS CATEGORY', 'TAX CLASS AT PRESENT', 
                   'BUILDING CLASS AT PRESENT', 'ZIP CODE', 'BUILDING CLASS AT TIME OF SALE']

nominal_prefixes = ['B', 'N', 'BCC', 'TCP', 'BCP', 'ZC', 'BCTS']

X = onehot_encode(X, nominal_features, nominal_prefixes)

In [47]:
X

,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,YEAR,MONTH,DAY,B_1,B_2,B_3,B_4,B_5,N_AIRPORT LA GUARDIA,N_ALPHABET CITY,N_ANNADALE,N_ARDEN HEIGHTS,N_ARROCHAR,N_ARROCHAR-SHORE ACRES,N_ARVERNE,N_ASTORIA,N_BATH BEACH,N_BATHGATE,N_BAY RIDGE,N_BAYCHESTER,N_BAYSIDE,N_BEDFORD PARK/NORWOOD,N_BEDFORD STUYVESANT,N_BEECHHURST,N_BELLE HARBOR,N_BELLEROSE,N_BELMONT,N_BENSONHURST,N_BERGEN BEACH,N_BLOOMFIELD,N_BOERUM HILL,N_BOROUGH PARK,N_BRIARWOOD,N_BRIGHTON BEACH,N_BROAD CHANNEL,N_BRONX PARK,N_BRONXDALE,N_BROOKLYN HEIGHTS,N_BROWNSVILLE,N_BULLS HEAD,N_BUSH TERMINAL,N_BUSHWICK,N_CAMBRIA HEIGHTS,N_CANARSIE,N_CARROLL GARDENS,N_CASTLE HILL/UNIONPORT,N_CASTLETON CORNERS,N_CHELSEA,N_CHINATOWN,N_CITY ISLAND,N_CITY ISLAND-PELHAM STRIP,N_CIVIC CENTER,N_CLINTON,N_CLINTON HILL,N_CLOVE LAKES,N_CO-OP CITY,N_COBBLE HILL,N_COBBLE HILL-WEST,N_COLLEGE POINT,N_CONCORD,N_CONCORD-FOX HILLS,N_CONEY ISLAND,N_CORONA,N_COUNTRY CLUB,N_CROTONA PARK,N_CROWN HEIGHTS,N_CYPRESS HILLS,N_DONGAN HILLS,N_DONGAN HILLS-COLONY,N_DONGAN HILLS-OLD TOWN,N_DOUGLASTON,N_DOWNTOWN-FULTON FERRY,N_DOWNTOWN-FULTON MALL,N_DOWNTOWN-METROTECH,N_DYKER HEIGHTS,N_EAST ELMHURST,N_EAST NEW YORK,N_EAST RIVER,N_EAST TREMONT,N_EAST VILLAGE,N_ELMHURST,N_ELTINGVILLE,N_EMERSON HILL,N_FAR ROCKAWAY,N_FASHION,N_FIELDSTON,N_FINANCIAL,N_FLATBUSH-CENTRAL,N_FLATBUSH-EAST,N_FLATBUSH-LEFFERTS GARDEN,N_FLATBUSH-NORTH,N_FLATIRON,N_FLATLANDS,N_FLORAL PARK,N_FLUSHING MEADOW PARK,N_FLUSHING-NORTH,N_FLUSHING-SOUTH,N_FORDHAM,N_FOREST HILLS,N_FORT GREENE,N_FRESH KILLS,N_FRESH MEADOWS,N_GERRITSEN BEACH,N_GLEN OAKS,N_GLENDALE,N_GOWANUS,N_GRAMERCY,N_GRANT CITY,N_GRASMERE,N_GRAVESEND,N_GREAT KILLS,N_GREAT KILLS-BAY TERRACE,N_GREENPOINT,N_GREENWICH VILLAGE-CENTRAL,N_GREENWICH VILLAGE-WEST,N_GRYMES HILL,N_HAMMELS,N_HARLEM-CENTRAL,N_HARLEM-EAST,N_HARLEM-UPPER,N_HARLEM-WEST,N_HIGHBRIDGE/MORRIS HEIGHTS,N_HILLCREST,N_HOLLIS,N_HOLLIS HILLS,N_HOLLISWOOD,N_HOWARD BEACH,N_HUGUENOT,N_HUNTS POINT,N_INWOOD,N_JACKSON HEIGHTS,N_JAMAICA,N_JAMAICA BAY,N_JAMAICA ESTATES,N_JAMAICA HILLS,N_JAVITS CENTER,N_KENSINGTON,N_KEW GARDENS,N_KINGSBRIDGE HTS/UNIV HTS,N_KINGSBRIDGE/JEROME PARK,N_KIPS BAY,N_LAURELTON,N_LITTLE ITALY,N_LITTLE NECK,N_LIVINGSTON,N_LONG ISLAND CITY,N_LOWER EAST SIDE,N_MADISON,N_MANHATTAN BEACH,N_MANHATTAN VALLEY,N_MANOR HEIGHTS,N_MARINE PARK,N_MARINERS HARBOR,N_MASPETH,N_MELROSE/CONCOURSE,N_MIDDLE VILLAGE,N_MIDLAND BEACH,N_MIDTOWN CBD,N_MIDTOWN EAST,N_MIDTOWN WEST,N_MIDWOOD,N_MILL BASIN,N_MORNINGSIDE HEIGHTS,N_MORRIS PARK/VAN NEST,N_MORRISANIA/LONGWOOD,N_MOTT HAVEN/PORT MORRIS,N_MOUNT HOPE/MOUNT EDEN,N_MURRAY HILL,N_NAVY YARD,N_NEPONSIT,N_NEW BRIGHTON,N_NEW BRIGHTON-ST. GEORGE,N_NEW DORP,N_NEW DORP-BEACH,N_NEW DORP-HEIGHTS,N_NEW SPRINGVILLE,N_OAKLAND GARDENS,N_OAKWOOD,N_OAKWOOD-BEACH,N_OCEAN HILL,N_OCEAN PARKWAY-NORTH,N_OCEAN PARKWAY-SOUTH,N_OLD MILL BASIN,N_OZONE PARK,N_PARK SLOPE,N_PARK SLOPE SOUTH,N_PARKCHESTER,N_PELHAM BAY,N_PELHAM GARDENS,N_PELHAM PARKWAY NORTH,N_PELHAM PARKWAY SOUTH,N_PLEASANT PLAINS,N_PORT IVORY,N_PORT RICHMOND,N_PRINCES BAY,N_PROSPECT HEIGHTS,N_QUEENS VILLAGE,N_RED HOOK,N_REGO PARK,N_RICHMOND HILL,N_RICHMONDTOWN,N_RICHMONDTOWN-LIGHTHS HILL,N_RIDGEWOOD,N_RIVERDALE,N_ROCKAWAY PARK,N_ROOSEVELT ISLAND,N_ROSEBANK,N_ROSEDALE,N_ROSSVILLE,N_ROSSVILLE-CHARLESTON,N_ROSSVILLE-PORT MOBIL,N_ROSSVILLE-RICHMOND VALLEY,N_SCHUYLERVILLE/PELHAM BAY,N_SEAGATE,N_SHEEPSHEAD BAY,N_SILVER LAKE,N_SO. JAMAICA-BAISLEY PARK,N_SOHO,N_SOUNDVIEW,N_SOUTH BEACH,N_SOUTH JAMAICA,N_SOUTH OZONE PARK,N_SOUTHBRIDGE,N_SPRING CREEK,N_SPRINGFIELD GARDENS,N_ST. ALBANS,N_STAPLETON,N_STAPLETON-CLIFTON,N_SUNNYSIDE,N_SUNSET PARK,N_THROGS NECK,N_TODT HILL,N_TOMPKINSVILLE,N_TOTTENVILLE,N_TRAVIS,N_TRIBECA,N_UPPER EAST SIDE (59-79),N_UPPER EAST SIDE (79-96),N_UPPER EAST SIDE (96-110),N_UPPER WEST SIDE (59-79),N_UPPER WEST SIDE (79-96),N_UPPER WEST SIDE (96-116),N_VAN CORTLANDT PARK,N_WAKEFIELD,N_WASHINGTON HEIGHTS LOWER,N_WASHINGTON HEIGHTS UPPER,N_WEST NEW BRIGHTON,N_WESTCHESTER,N_WESTERLEIGH,N_WHITESTONE,N_WILLIAMSBRIDGE,N_WILLIAMSBURG-CENTRAL,N_WILLIAMSBURG-EAST,N_WILLIAMSBURG-NORTH,N_WILLIAMSBURG-SOUTH,N_WILLOWBROOK,N_WINDSOR TERRACE,N_WOODHAVEN,N_WOODLAWN,N_WOODROW,N_WOODSIDE,N_WYCKOFF HEIGHTS,BCC_01 ONE FAMILY DWELLINGS,BCC_02 TWO FAMILY DWELLINGS,BCC_03 THREE FAMILY DWELLINGS,BCC_04 TAX CLASS 1 CONDOS,BCC_05 TAX CLASS 1 VACANT LAND,BCC_06 TAX CLASS 1 - OTHER,BCC_07 RENTALS - WALKUP APARTMENTS,BCC_08 RENTALS - ELEVATOR APARTMENTS,BCC_09 COOPS - WALKUP APARTMENTS,BCC_10 COOPS - ELEVATOR APARTMENTS,BCC_11 SPECIAL CONDO BILLING LOTS,BCC_11A CONDO-RENTALS,BCC_12 CONDOS - WALKUP APARTMENTS,BCC_13 CONDOS - ELEVATOR APARTMENTS,BCC_14 RENTALS - 4-10 UNIT,BCC_15 CONDOS - 2-10 UNIT RESIDENTIAL,BCC_16 CONDOS - 2-10 UNIT WITH COMMERCIAL UNIT,BCC_17 CONDO COOPS,BCC_18 TAX CLASS 3 - UNTILITY PROPERTIES,BCC_21 OFFICE BUILDINGS,BCC_22 STORE BUILDINGS,BCC_23 LOFT BUILDINGS,BCC_25 LUXURY HOTELS,BCC_26 OTHER HOTELS,BCC_27 FACTORIES,BCC_28 COMMERCIAL CONDOS,BCC_29 COMMERCIAL GARAGES,BCC_30 WAREHOUSES,BCC_31 COMMERCIAL VACANT LAND,BCC_32 HOSPITAL AND HEALTH FACILITIES,BCC_33 EDUCATIONAL FACILITIES,BCC_34 THEATRES,BCC_35 INDOOR PUBLIC AND CULTURAL FACILITIES,BCC_36 OUTDOOR RECREATIONAL FACILITIES,BCC_37 RELIGIOUS FACILITIES,BCC_38 ASYLUMS AND HOMES,BCC_39 TRANSPORTATION FACILITIES,BCC_40 SELECTED GOVERNMENTAL FACILITIES,BCC_41 TAX CLASS 4 - OTHER,BCC_42 CONDO CULTURAL/MEDICAL/EDUCATIONAL/ETC,BCC_43 CONDO OFFICE BUILDINGS,BCC_44 CONDO PARKING,BCC_45 CONDO HOTELS,BCC_46 CONDO STORE BUILDINGS,BCC_47 CONDO NON-BUSINESS STORAGE,BCC_48 CONDO TERRACES/GARDENS/CABANAS,BCC_49 CONDO WAREHOUSES/FACTORY/INDUS,TCP_,TCP_1,TCP_1A,TCP_1B,TCP_1C,TCP_2,TCP_2A,TCP_2B,TCP_2C,TCP_3,TCP_4,BCP_,BCP_A0,BCP_A1,BCP_A2,BCP_A3,BCP_A4,BCP_A5,BCP_A6,BCP_A7,BCP_A9,BCP_B1,BCP_B2,BCP_B3,BCP_B9,BCP_C0,BCP_C1,BCP_C2,BCP_C3,BCP_C4,BCP_C5,BCP_C6,BCP_C7,BCP_C8,BCP_C9,BCP_CM,BCP_D0,BCP_D1,BCP_D2,BCP_D3,BCP_D4,BCP_D5,BCP_D6,BCP_D7,BCP_D8,BCP_D9,BCP_E1,BCP_E2,BCP_E7,BCP_E9,BCP_F1,BCP_F2,BCP_F4,BCP_F5,BCP_F9,BCP_G0,BCP_G1,BCP_G2,BCP_G3,BCP_G4,BCP_G5,BCP_G6,BCP_G7,BCP_G8,BCP_G9,BCP_GU,BCP_GW,BCP_H1,BCP_H2,BCP_H3,BCP_H4,BCP_H6,BCP_H8,BCP_H9,BCP_HB,BCP_HH,BCP_HR,BCP_HS,BCP_I1,BCP_I3,BCP_I4,BCP_I5,BCP_I6,BCP_I7,BCP_I9,BCP_J1,BCP_J4,BCP_J8,BCP_K1,BCP_K2,BCP_K3,BCP_K4,BCP_K5,BCP_K6,BCP_K7,BCP_K8,BCP_K9,BCP_L1,BCP_L3,BCP_L8,BCP_L9,BCP_M1,BCP_M2,BCP_M3,BCP_M4,BCP_M9,BCP_N2,BCP_N9,BCP_O1,BCP_O2,BCP_O3,BCP_O4,BCP_O5,BCP_O6,BCP_O7,BCP_O8,BCP_O9,BCP_P2,BCP_P5,BCP_P6,BCP_P8,BCP_P9,BCP_Q1,BCP_Q8,BCP_Q9,BCP_R0,BCP_R1,BCP_R2,BCP_R3,BCP_R4,BCP_R5,BCP_R6,BCP_R7,BCP_R8,BCP_R9,BCP_RA,BCP_RB,BCP_RG,BCP_RH,BCP_RK,BCP_RP,BCP_RR,BCP_RS,BCP_RT,BCP_RW,BCP_S0,BCP_S1,BCP_S2,BCP_S3,BCP_S4,BCP_S5,BCP_S9,BCP_T2,BCP_U1,BCP_V0,BCP_V1,BCP_V2,BCP_V3,BCP_V6,BCP_V9,BCP_W1,BCP_W2,BCP_W3,BCP_W4,BCP_W6,BCP_W8,BCP_W9,BCP_Y1,BCP_Y3,BCP_Z0,BCP_Z2,BCP_Z9,ZC_0,ZC_10001,ZC_10002,ZC_10003,ZC_10004,ZC_10005,ZC_10006,ZC_10007,ZC_10009,ZC_10010,ZC_10011,ZC_10012,ZC_10013,ZC_10014,ZC_10016,ZC_10017,ZC_10018,ZC_10019,ZC_10021,ZC_10022,ZC_10023,ZC_10024,ZC_10025,ZC_10026,ZC_10027,ZC_10028,ZC_10029,ZC_10030,ZC_10031,ZC_10032,ZC_10033,ZC_10034,ZC_10035,ZC_10036,ZC_10037,ZC_10038,ZC_10039,ZC_10040,ZC_10044,ZC_10065,ZC_10069,ZC_10075,ZC_10105,ZC_10128,ZC_10167,ZC_10280,ZC_10282,ZC_10301,ZC_10302,ZC_10303,ZC_10304,ZC_10305,ZC_10306,ZC_10307,ZC_10308,ZC_10309,ZC_10310,ZC_10312,ZC_10314,ZC_10451,ZC_10452,ZC_10453,ZC_10454,ZC_10455,ZC_10456,ZC_10457,ZC_10458,ZC_10459,ZC_10460,ZC_10461,ZC_10462,ZC_10463,ZC_10464,ZC_10465,ZC_10466,ZC_10467,ZC_10468,ZC_10469,ZC_10470,ZC_10471,ZC_10472,ZC_10473,ZC_10474,ZC_10475,ZC_10803,ZC_11001,ZC_11004,ZC_11005,ZC_11040,ZC_11101,ZC_11102,ZC_11103,ZC_11104,ZC_11105,ZC_11106,ZC_11109,ZC_11201,ZC_11203,ZC_11204,ZC_11205,ZC_11206,ZC_11207,ZC_11208,ZC_11209,ZC_11210,ZC_11211,ZC_11212,ZC_11213,ZC_11214,ZC_11215,ZC_11216,ZC_11217,ZC_11218,ZC_11219,ZC_11220,ZC_11221,ZC_11222,ZC_11223,ZC_11224,ZC_11225,ZC_11226,ZC_11228,ZC_11229,ZC_11230,ZC_11231,ZC_11232,ZC_11233,ZC_11234,ZC_11235,ZC_11236,ZC_11237,ZC_11238,ZC_11239,ZC_11249,ZC_11354,ZC_11355,ZC_11356,ZC_11357,ZC_11358,ZC_11360,ZC_11361,ZC_11362,ZC_11363,ZC_11364,ZC_11365,ZC_11366,ZC_11367,ZC_11368,ZC_11369,ZC_11370,ZC_11372,ZC_11373,ZC_11374,ZC_11375,ZC_11377,ZC_11378,ZC_11379,ZC_11385,ZC_11411,ZC_11412,ZC_11413,ZC_11414,ZC_11415,ZC_11416,ZC_11417,ZC_11418,ZC_11419,ZC_11420,ZC_11421,ZC_11422,ZC_11423,ZC_11426,ZC_11427,ZC_11428,ZC_11429,ZC_11432,ZC_11433,ZC_11434,ZC_11435,ZC_11436,ZC_11691,ZC_11692,ZC_11693,ZC_11694,BCTS_A0,BCTS_A1,BCTS_A2,BCTS_A3,BCTS_A4,BCTS_A5,BCTS_A6,BCTS_A7,BCTS_A9,BCTS_B1,BCTS_B2,BCTS_B3,BCTS_B9,BCTS_C0,BCTS_C1,BCTS_C2,BCTS_C3,BCTS_C4,BCTS_C5,BCTS_C6,BCTS_C7,BCTS_C8,BCTS_C9,BCTS_CM,BCTS_D0,BCTS_D1,BCTS_D2,BCTS_D3,BCTS_D4,BCTS_D5,BCTS_D6,BCTS_D7,BCTS_D8,BCTS_D9,BCTS_E1,BCTS_E2,BCTS_E7,BCTS_E9,BCTS_F1,BCTS_F2,BCTS_F4,BCTS_F5,BCTS_F9,BCTS_G0,BCTS_G1,BCTS_G2,BCTS_G3,BCTS_G4,BCTS_G5,BCTS_G6,BCTS_G7,BCTS_G8,BCTS_G9,BCTS_GU,BCTS_GW,BCTS_H1,BCTS_H2,BCTS_H3,BCTS_H4,BCTS_H6,BCTS_H8,BCTS_H9,BCTS_HB,BCTS_HH,BCTS_HR,BCTS_HS,BCTS_I1,BCTS_I3,BCTS_I4,BCTS_I5,BCTS_I6,BCTS_I7,BCTS_I9,BCTS_J1,BCTS_J4,BCTS_J8,BCTS_J9,BCTS_K1,BCTS_K2,BCTS_K3,BCTS_K4,BCTS_K5,BCTS_K6,BCTS_K7,BCTS_K8,BCTS_K9,BCTS_L1,BCTS_L3,BCTS_L8,BCTS_L9,BCTS_M1,BCTS_M2,BCTS_M3,BCTS_M4,BCTS_M9,BCTS_N2,BCTS_N9,BCTS_O1,BCTS_O2,BCTS_O3,BCTS_O4,BCTS_O5,BCTS_O6,BCTS_O7,BCTS_O8,BCTS_O9,BCTS_P2,BCTS_P5,BCTS_P6,BCTS_P8,BCTS_P9,BCTS_Q1,BCTS_Q8,BCTS_Q9,BCTS_R0,BCTS_R1,BCTS_R2,BCTS_R3,BCTS_R4,BCTS_R5,BCTS_R6,BCTS_R7,BCTS_R8,BCTS_R9,BCTS_RA,BCTS_RB,BCTS_RG,BCTS_RH,BCTS_RK,BCTS_RP,BCTS_RR,BCTS_RS,BCTS_RT,BCTS_RW,BCTS_S0,BCTS_S1,BCTS_S2,BCTS_S3,BCTS_S4,BCTS_S5,BCTS_S9,BCTS_T2,BCTS_U1,BCTS_V0,BCTS_V1,BCTS_V2,BCTS_V3,BCTS_V6,BCTS_V9,BCTS_W1,BCTS_W2,BCTS_W3,BCTS_W4,BCTS_W6,BCTS_W8,BCTS_W9,BCTS_Y1,BCTS_Y3,BCTS_Z0,BCTS_Z2,BCTS_Z9
0,5,0,5,1633.0,6440.0,1900,2,2017,7,19,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,10,0,10,2272.0,6794.0,1913,2,2016,9,23,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,6,0,6,2369.0,4615.0,1900,2,2016,11,17,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,8,0,8,1750.0,4226.0,1920,2,2016,9,23,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,24,0,24,4489.0,18523.0,1920,2,2016,11,7,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [48]:
y

0         6625000.0
1         3936272.0
2         8000000.0
3         3192840.0
4        16232000.0
            ...
69982      450000.0
69983      550000.0
69984      460000.0
69985    11693337.0
69986       69300.0
Name: SALE PRICE, Length: 69987, dtype: float64

In [49]:
# Scale X with a standard scaler
scaler = StandardScaler()

X = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)

### Training

In [52]:
# Train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=123)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, train_size=0.7, random_state=123)

In [53]:
dtrain = xgb.DMatrix(X_train, label=y_train)
dval = xgb.DMatrix(X_val, label=y_val)
dtest = xgb.DMatrix(X_test, label=y_test)

In [55]:
params = {'learning_rate': 0.001, 'max_depth': 6, 'lambda': 0.01}

model = xgb.train(params, dtrain, num_boost_round=10000, evals=[(dval, 'eval')], early_stopping_rounds=10)

[0]	eval-rmse:6350362.70889
[1]	eval-rmse:6349248.69355
[2]	eval-rmse:6348144.20980
[3]	eval-rmse:6347049.31016
[4]	eval-rmse:6345963.93568
[5]	eval-rmse:6344887.94717
[6]	eval-rmse:6343821.43550
[7]	eval-rmse:6342764.32470
[8]	eval-rmse:6341716.58966
[9]	eval-rmse:6340678.35005
[10]	eval-rmse:6339649.34158
[11]	eval-rmse:6338629.63553
[12]	eval-rmse:6337619.31223
[13]	eval-rmse:6336618.14126
[14]	eval-rmse:6335626.33901
[15]	eval-rmse:6334643.89021
[16]	eval-rmse:6333670.51865
[17]	eval-rmse:6332706.22044
[18]	eval-rmse:6331751.28429
[19]	eval-rmse:6330805.49344
[20]	eval-rmse:6329868.74817
[21]	eval-rmse:6328941.25676
[22]	eval-rmse:6328022.76357
[23]	eval-rmse:6327113.31700
[24]	eval-rmse:6326213.02110
[25]	eval-rmse:6325321.68369
[26]	eval-rmse:6324439.31732
[27]	eval-rmse:6323565.86446
[28]	eval-rmse:6322701.59194
[29]	eval-rmse:6321846.10860
[30]	eval-rmse:6320999.62601
[31]	eval-rmse:6320161.94304
[32]	eval-rmse:6319333.30268
[33]	eval-rmse:6318513.28773
[34]	eval-rmse:6317702.22716
[35]	eval-rmse:6316900.04262
[36]	eval-rmse:6316106.48208
[37]	eval-rmse:6315321.77097
[38]	eval-rmse:6314545.75869
[39]	eval-rmse:6313778.56236
[40]	eval-rmse:6313019.98604
[41]	eval-rmse:6312270.11965
[42]	eval-rmse:6311529.03175
[43]	eval-rmse:6310796.43017
[44]	eval-rmse:6310072.49545
[45]	eval-rmse:6309357.17949
[46]	eval-rmse:6308650.35265
[47]	eval-rmse:6307952.16985
[48]	eval-rmse:6307262.35175
[49]	eval-rmse:6306581.28933
[50]	eval-rmse:6305908.58917
[51]	eval-rmse:6305246.78960
[52]	eval-rmse:6304590.79996
[53]	eval-rmse:6303945.81857
[54]	eval-rmse:6303306.47206
[55]	eval-rmse:6302678.04477
[56]	eval-rmse:6302055.23705
[57]	eval-rmse:6301467.25638
[58]	eval-rmse:6300863.69085
[59]	eval-rmse:6300265.40688
[60]	eval-rmse:6299702.09997
[61]	eval-rmse:6299120.17804
[62]	eval-rmse:6298572.96523
[63]	eval-rmse:6298007.29523
[64]	eval-rmse:6297476.34413
[65]	eval-rmse:6296926.89413
[66]	eval-rmse:6296411.91608
[67]	eval-rmse:6295881.25447
[68]	eval-rmse:6295355.66816
[69]	eval-rmse:6294864.69621
[70]	eval-rmse:6294399.16619
[71]	eval-rmse:6293924.07472
[72]	eval-rmse:6293474.18546
[73]	eval-rmse:6293015.02766
[74]	eval-rmse:6292580.83992
[75]	eval-rmse:6292137.31163
[76]	eval-rmse:6291677.81764
[77]	eval-rmse:6291267.04021
[78]	eval-rmse:6290846.95308
[79]	eval-rmse:6290451.62800
[80]	eval-rmse:6290047.12069
[81]	eval-rmse:6289667.17575
[82]	eval-rmse:6289277.94858
[83]	eval-rmse:6288913.37747
[84]	eval-rmse:6288539.40233
[85]	eval-rmse:6288190.05459
[86]	eval-rmse:6287831.48717
[87]	eval-rmse:6287456.82884
[88]	eval-rmse:6287130.26308
[89]	eval-rmse:6286794.31609
[90]	eval-rmse:6286482.68445
[91]	eval-rmse:6286161.95557
[92]	eval-rmse:6285865.30031
[93]	eval-rmse:6285559.32933
[94]	eval-rmse:6285277.56578
[95]	eval-rmse:6284986.51200
[96]	eval-rmse:6284679.62930
[97]	eval-rmse:6284419.90894
[98]	eval-rmse:6284151.10823
[99]	eval-rmse:6283906.18487
[100]	eval-rmse:6283651.98376
[101]	eval-rmse:6283421.56768
[102]	eval-rmse:6283182.11053
[103]	eval-rmse:6282966.11210
[104]	eval-rmse:6282741.10491
[105]	eval-rmse:6282500.05426
[106]	eval-rmse:6282305.63575
[107]	eval-rmse:6282102.30569
[108]	eval-rmse:6281922.34948
[109]	eval-rmse:6281733.24649
[110]	eval-rmse:6281567.39227
[111]	eval-rmse:6281392.52229
[112]	eval-rmse:6281224.85131
[113]	eval-rmse:6281080.14374
[114]	eval-rmse:6280903.37630
[115]	eval-rmse:6280772.80943
[116]	eval-rmse:6280633.21713
[117]	eval-rmse:6280516.37873
[118]	eval-rmse:6280390.84819
[119]	eval-rmse:6280287.95948
[120]	eval-rmse:6280176.18676
[121]	eval-rmse:6280071.48195
[122]	eval-rmse:6279989.12829
[123]	eval-rmse:6279903.61277
[124]	eval-rmse:6279834.80036
[125]	eval-rmse:6279734.17623
[126]	eval-rmse:6279679.12375
[127]	eval-rmse:6279620.38018
[128]	eval-rmse:6279578.66270
[129]	eval-rmse:6279533.21671
[130]	eval-rmse:6279494.63401
[131]	eval-rmse:6279472.69108
[132]	eval-rmse:6279447.52645
[133]	eval-rmse:6279438.52403
[134]	eval-rmse:6279426.48469
[135]	eval-rmse:6279430.75253
[136]	eval-rmse:6279403.48676
[137]	eval-rmse:6279411.05731
[138]	eval-rmse:6279434.80562
[139]	eval-rmse:6279455.27402
[140]	eval-rmse:6279492.01020
[141]	eval-rmse:6279525.39708
[142]	eval-rmse:6279574.93953
[143]	eval-rmse:6279621.21495
[144]	eval-rmse:6279683.48565
[145]	eval-rmse:6279714.27715
[146]	eval-rmse:6279779.77304

In [56]:
y_true = np.array(y_test)
y_pred = model.predict(dtest)

In [57]:
print("Model R^2 Score: {:.4f}".format(r2_score(y_true, y_pred)))

Model R^2 Score: 0.0554