## Financial Distress Prediction (Regression)

Given *data about various companies*, let's try to predict a given company's **financial distress level**.

We will use a linear regression model and a gradient boosting model to make our predictions.

Data source: https://www.kaggle.com/datasets/shebrahimi/financial-distress

### Importing Libraries

In [4]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
import xgboost as xgb

from sklearn.metrics import r2_score

pd.set_option('display.max_columns', None)

In [18]:
data = pd.read_csv('archive/Financial Distress.csv')
data

,Company,Time,Financial Distress,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22,x23,x24,x25,x26,x27,x28,x29,x30,x31,x32,x33,x34,x35,x36,x37,x38,x39,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49,x50,x51,x52,x53,x54,x55,x56,x57,x58,x59,x60,x61,x62,x63,x64,x65,x66,x67,x68,x69,x70,x71,x72,x73,x74,x75,x76,x77,x78,x79,x80,x81,x82,x83
0,1,1,0.010636,1.2810,0.022934,0.87454,1.21640,0.060940,0.188270,0.52510,0.018854,0.182790,0.006449,0.85822,2.005800e+00,0.125460,6.97060,4.65120,0.050100,2.1984,0.018265,0.024978,0.027264,1.41730,9.5554,0.148720,0.66995,214.760,12.641,6.46070,0.043835,0.204590,0.35179,8.316100,0.28922,0.76606,2.5825,77.400,0.026722,1.630700,0.015016,0.005478,0.127300,9.69510,-0.736220,0.98559,0.180160,1.50060,0.026224,7.05130,1174.90,5.33990,0.851280,12.837,0.061737,0.180900,209.87,-0.582550,0.471010,0.109900,0.000000,0.000000,0.22009,7.12410,15.38100,3.27020,17.8720,34.6920,30.087,12.8,7991.4,364.9500,15.8,61.476,4.0,36.0,85.437,27.07,26.102,16.000,16.0,0.2,22,0.060390,30,49
1,1,2,-0.455970,1.2700,0.006454,0.82067,1.00490,-0.014080,0.181040,0.62288,0.006423,0.035991,0.001795,0.85152,-4.864400e-01,0.179330,4.57640,3.75210,-0.014011,2.4575,0.027558,0.028804,0.041102,1.18010,7.2952,0.056026,0.67048,38.242,12.877,5.55060,0.265480,0.150190,0.41763,9.527600,0.41561,0.81699,2.6033,95.947,0.007580,0.837540,0.027425,0.045434,0.137740,5.60350,-0.643850,1.30190,0.046857,1.00950,0.007864,4.60220,1062.50,3.73890,0.943970,12.881,-0.000565,0.056298,250.14,-0.474770,0.385990,0.369330,0.000000,0.000000,0.00000,7.41660,7.10500,14.32100,18.7700,124.7600,26.124,11.8,8322.8,0.1896,15.6,24.579,0.0,36.0,107.090,31.31,30.194,17.000,16.0,0.4,22,0.010636,31,50
2,1,3,-0.325390,1.0529,-0.059379,0.92242,0.72926,0.020476,0.044865,0.43292,-0.081423,-0.765400,-0.054324,0.89314,4.122000e-01,0.077578,11.89000,2.48840,0.028077,1.3957,0.012595,0.068116,0.014847,0.81652,7.1204,0.065220,0.84827,-498.390,13.225,16.25400,0.416570,0.074149,0.36723,9.351300,0.50356,0.91962,1.4931,144.670,-0.066483,0.955790,0.017270,0.028059,0.102420,9.40030,-14.032000,0.75746,-0.579760,0.57832,-0.064373,11.98800,651.15,10.93400,0.934780,12.909,0.041625,0.047562,280.55,-1.000000,0.488440,0.053299,0.003785,0.005191,0.00000,3.63730,7.02130,1.15380,9.8951,6.4467,30.245,10.3,8747.0,11.9460,15.2,20.700,0.0,35.0,120.870,36.07,35.273,17.000,15.0,-0.2,22,-0.455970,32,51
3,1,4,-0.566570,1.1131,-0.015229,0.85888,0.80974,0.076037,0.091033,0.67546,-0.018807,-0.107910,-0.065316,0.89581,9.949000e-01,0.141120,6.08620,1.63820,0.093904,2.0588,0.011601,0.094385,0.014415,0.90391,7.9828,0.125160,0.80478,-75.867,13.305,8.89500,0.083774,0.054098,0.54360,7.090900,0.67133,0.93701,2.3533,219.750,-0.017000,0.383350,0.014327,0.203370,0.101430,5.73790,0.722050,1.39120,-0.150130,0.64508,-0.017731,6.11140,703.04,5.70280,0.874840,13.094,0.108400,0.101350,413.74,0.565000,0.344080,0.073356,0.000037,0.000045,0.00000,5.14420,9.90990,2.04080,-1.4903,-21.9070,34.285,11.5,9042.5,-18.7480,10.4,47.429,4.0,33.0,54.806,39.80,38.377,17.167,16.0,5.6,22,-0.325390,33,52
4,2,1,1.357300,1.0623,0.107020,0.81460,0.83593,0.199960,0.047800,0.74200,0.128030,0.577250,0.094075,0.81549,3.014700e+00,0.185400,4.39380,1.61690,0.239210,3.0311,0.006814,0.079346,0.008876,1.02510,4.7463,0.266020,0.76770,1423.100,11.575,17.48800,0.620770,0.046907,0.56963,9.486100,0.68143,0.94242,4.1296,222.650,0.131230,0.253010,0.008152,0.353010,0.176120,4.50880,-0.113390,1.05270,0.607660,0.25782,0.131380,4.41510,2465.40,4.14080,0.733980,11.396,0.250310,0.222370,315.34,-0.060101,0.202420,1.229100,-0.002491,-0.002980,0.22688,7.12410,15.38100,3.27020,17.8720,34.6920,30.087,12.8,7991.4,364.9500,15.8,61.476,4.0,36.0,85.437,27.07,26.102,16.000,16.0,0.2,29,1.251000,7,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3667,422,10,0.438020,2.2605,0.202890,0.16037,0.18588,0.175970,0.198400,2.22360,1.091500,0.241640,0.226860,0.35580,1.550000e+07,0.839630,0.19101,12.09200,0.946730,8.1062,0.014077,0.000000,0.089439,0.52242,2.5184,0.994340,0.15740,390.260,18.296,0.93687,-0.007698,0.002976,0.34999,0.013104,1.88290,0.98144,1431.7000,29.772,0.570230,0.003544,0.075736,0.362010,0.073807,0.22138,-0.114700,11.37600,2.748900,0.23629,1.265100,0.19102,1615.10,0.18746,0.005662,16.613,0.948040,0.184820,16961.00,-0.060838,0.000130,0.488130,0.000000,0.000000,0.00000,3.06210,3.95540,-0.53449,-9.3020,11.2070,20.132,12.3,13568.0,14.5290,21.5,33.768,2.0,22.0,100.000,100.00,100.000,17.125,14.5,-7.0,37,0.436380,4,41
3668,422,11,0.482410,1.9615,0.216440,0.20095,0.21642,0.203590,0.189870,1.93820,1.000100,0.270870,0.213610,0.38734,1.920000e+07,0.799050,0.25149,2.63990,0.940730,14.4280,0.018249,0.000000,0.092416,0.55872,2.7304,0.992440,0.19747,443.840,18.360,1.13980,0.066060,0.003484,0.38274,0.010072,1.76850,0.98267,1907.8000,136.370,0.558780,0.004359,0.084325,0.241230,0.079261,0.27085,0.137280,10.08100,2.730700,0.23762,1.077100,0.25152,1638.50,0.24713,0.007563,16.829,0.942850,0.214780,20689.00,0.064229,0.000113,0.144840,0.000000,0.000000,0.00000,-7.71400,-11.82400,-25.73600,-21.4110,46.8440,30.046,12.2,26059.0,3.8523,30.5,-10.665,0.0,28.0,91.500,130.50,132.400,20.000,14.5,-16.0,37,0.438020,5,42
3669,422,12,0.500770,1.7099,0.207970,0.26136,0.21399,0.193670,0.183890,1.68980,0.971860,0.281560,0.210970,0.44290,2.030000e+07,0.738640,0.35384,1.49010,0.905010,39.0520,0.007451,0.000000,0.028768,0.48316,2.9064,0.982420,0.25902,475.560,18.469,1.16370,0.115120,0.002343,0.43769,0.022285,2.04530,0.99104,2221.2000,241.600,0.469560,0.003172,0.034821,0.102630,0.073630,0.28971,0.071485,10.03200,2.824600,0.24895,0.795720,0.35392,1689.00,0.35067,0.017581,16.927,0.907060,0.210230,34012.00,0.034509,0.000096,0.035889,0.000000,0.000000,0.00000,-0.32511,-0.71099,-3.06590,-17.8990,107.7100,38.823,10.4,31839.0,-25.8410,34.7,36.030,2.0,32.0,87.100,175.90,178.100,20.000,14.5,-20.2,37,0.482410,6,43
3670,422,13,0.611030,1.5590,0.185450,0.30728,0.19307,0.172140,0.170680,1.53890,0.960570,0.267720,0.203190,0.47601,1.099600e+02,0.692720,0.44358,1.38370,0.891630,39.6790,0.021239,0.008109,0.069562,0.40559,2.5221,0.985230,0.30533,457.060,18.543,1.13120,0.077785,0.001942,0.46988,0.023538,2.43380,0.99368,2685.8000,260.160,0.389600,0.002803,0.110010,-0.027616,0.076549,0.27871,-0.038907,9.04940,2.422700,0.24639,0.603540,0.44367,1707.30,0.44077,0.014773,16.899,0.894050,0.190210,35901.00,-0.019839,0.000072,0.120520,-0.001503,-0.007784,0.00000,3.21480,1.57190,7.15620,-4.5408,-20.8610,22.334,10.6,32801.0,-58.1220,15.6,22.571,2.0,30.0,92.900,203.20,204.500,22.000,22.0,6.4,37,0.500770,7,44
3671,422,14,0.518650,1.6148,0.176760,0.36369,0.18442,0.169550,0.197860,1.58420,0.958450,0.277780,0.213850,0.51969,1.542500e+01,0.636310,0.57156,0.42332,0.919350,15.0160,0.013783,0.059602,0.042826,0.35486,2.0440,0.994000,0.32184,505.040,18.691,0.93207,0.159350,0.041852,0.50985,0.006937,2.76460,0.88492,2500.8000,850.420,0.340120,0.065773,0.074738,0.107420,0.090225,0.28982,0.104980,7.05250,1.959100,0.31095,0.486010,0.57173,1818.10,0.50578,0.006004,17.001,0.922070,0.183310,28173.00,0.049872,0.000074,0.366480,0.001826,0.009902,0.00000,-1.58630,-7.50460,12.14500,-20.2290,28.2860,30.023,11.0,34501.0,-32.2090,11.9,13.871,1.0,29.0,91.700,227.50,214.500,21.000,20.5,8.6,37,0.611030,8,45

### Preprocessing

In [19]:
print("Total missing values:", data.isna().sum().sum())

Total missing values: 0

In [20]:
data = data.drop(['Company', 'Time'], axis=1)

In [21]:
def onehot_encode(df, column):
    df = df.copy()
    dummies = pd.get_dummies(df[column], prefix=column, dtype=int)
    df = pd.concat([df, dummies], axis=1)
    df = df.drop(column, axis=1)
    return df

In [22]:
data = onehot_encode(data, 'x80')
data

,Financial Distress,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22,x23,x24,x25,x26,x27,x28,x29,x30,x31,x32,x33,x34,x35,x36,x37,x38,x39,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49,x50,x51,x52,x53,x54,x55,x56,x57,x58,x59,x60,x61,x62,x63,x64,x65,x66,x67,x68,x69,x70,x71,x72,x73,x74,x75,x76,x77,x78,x79,x81,x82,x83,x80_1,x80_2,x80_3,x80_4,x80_5,x80_6,x80_7,x80_8,x80_9,x80_10,x80_11,x80_12,x80_13,x80_14,x80_15,x80_16,x80_17,x80_18,x80_19,x80_20,x80_21,x80_22,x80_23,x80_24,x80_25,x80_26,x80_27,x80_28,x80_29,x80_30,x80_31,x80_32,x80_33,x80_34,x80_35,x80_36,x80_37
0,0.010636,1.2810,0.022934,0.87454,1.21640,0.060940,0.188270,0.52510,0.018854,0.182790,0.006449,0.85822,2.005800e+00,0.125460,6.97060,4.65120,0.050100,2.1984,0.018265,0.024978,0.027264,1.41730,9.5554,0.148720,0.66995,214.760,12.641,6.46070,0.043835,0.204590,0.35179,8.316100,0.28922,0.76606,2.5825,77.400,0.026722,1.630700,0.015016,0.005478,0.127300,9.69510,-0.736220,0.98559,0.180160,1.50060,0.026224,7.05130,1174.90,5.33990,0.851280,12.837,0.061737,0.180900,209.87,-0.582550,0.471010,0.109900,0.000000,0.000000,0.22009,7.12410,15.38100,3.27020,17.8720,34.6920,30.087,12.8,7991.4,364.9500,15.8,61.476,4.0,36.0,85.437,27.07,26.102,16.000,16.0,0.2,0.060390,30,49,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,-0.455970,1.2700,0.006454,0.82067,1.00490,-0.014080,0.181040,0.62288,0.006423,0.035991,0.001795,0.85152,-4.864400e-01,0.179330,4.57640,3.75210,-0.014011,2.4575,0.027558,0.028804,0.041102,1.18010,7.2952,0.056026,0.67048,38.242,12.877,5.55060,0.265480,0.150190,0.41763,9.527600,0.41561,0.81699,2.6033,95.947,0.007580,0.837540,0.027425,0.045434,0.137740,5.60350,-0.643850,1.30190,0.046857,1.00950,0.007864,4.60220,1062.50,3.73890,0.943970,12.881,-0.000565,0.056298,250.14,-0.474770,0.385990,0.369330,0.000000,0.000000,0.00000,7.41660,7.10500,14.32100,18.7700,124.7600,26.124,11.8,8322.8,0.1896,15.6,24.579,0.0,36.0,107.090,31.31,30.194,17.000,16.0,0.4,0.010636,31,50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,-0.325390,1.0529,-0.059379,0.92242,0.72926,0.020476,0.044865,0.43292,-0.081423,-0.765400,-0.054324,0.89314,4.122000e-01,0.077578,11.89000,2.48840,0.028077,1.3957,0.012595,0.068116,0.014847,0.81652,7.1204,0.065220,0.84827,-498.390,13.225,16.25400,0.416570,0.074149,0.36723,9.351300,0.50356,0.91962,1.4931,144.670,-0.066483,0.955790,0.017270,0.028059,0.102420,9.40030,-14.032000,0.75746,-0.579760,0.57832,-0.064373,11.98800,651.15,10.93400,0.934780,12.909,0.041625,0.047562,280.55,-1.000000,0.488440,0.053299,0.003785,0.005191,0.00000,3.63730,7.02130,1.15380,9.8951,6.4467,30.245,10.3,8747.0,11.9460,15.2,20.700,0.0,35.0,120.870,36.07,35.273,17.000,15.0,-0.2,-0.455970,32,51,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,-0.566570,1.1131,-0.015229,0.85888,0.80974,0.076037,0.091033,0.67546,-0.018807,-0.107910,-0.065316,0.89581,9.949000e-01,0.141120,6.08620,1.63820,0.093904,2.0588,0.011601,0.094385,0.014415,0.90391,7.9828,0.125160,0.80478,-75.867,13.305,8.89500,0.083774,0.054098,0.54360,7.090900,0.67133,0.93701,2.3533,219.750,-0.017000,0.383350,0.014327,0.203370,0.101430,5.73790,0.722050,1.39120,-0.150130,0.64508,-0.017731,6.11140,703.04,5.70280,0.874840,13.094,0.108400,0.101350,413.74,0.565000,0.344080,0.073356,0.000037,0.000045,0.00000,5.14420,9.90990,2.04080,-1.4903,-21.9070,34.285,11.5,9042.5,-18.7480,10.4,47.429,4.0,33.0,54.806,39.80,38.377,17.167,16.0,5.6,-0.325390,33,52,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,1.357300,1.0623,0.107020,0.81460,0.83593,0.199960,0.047800,0.74200,0.128030,0.577250,0.094075,0.81549,3.014700e+00,0.185400,4.39380,1.61690,0.239210,3.0311,0.006814,0.079346,0.008876,1.02510,4.7463,0.266020,0.76770,1423.100,11.575,17.48800,0.620770,0.046907,0.56963,9.486100,0.68143,0.94242,4.1296,222.650,0.131230,0.253010,0.008152,0.353010,0.176120,4.50880,-0.113390,1.05270,0.607660,0.25782,0.131380,4.41510,2465.40,4.14080,0.733980,11.396,0.250310,0.222370,315.34,-0.060101,0.202420,1.229100,-0.002491,-0.002980,0.22688,7.12410,15.38100,3.27020,17.8720,34.6920,30.087,12.8,7991.4,364.9500,15.8,61.476,4.0,36.0,85.437,27.07,26.102,16.000,16.0,0.2,1.251000,7,27,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3667,0.438020,2.2605,0.202890,0.16037,0.18588,0.175970,0.198400,2.22360,1.091500,0.241640,0.226860,0.35580,1.550000e+07,0.839630,0.19101,12.09200,0.946730,8.1062,0.014077,0.000000,0.089439,0.52242,2.5184,0.994340,0.15740,390.260,18.296,0.93687,-0.007698,0.002976,0.34999,0.013104,1.88290,0.98144,1431.7000,29.772,0.570230,0.003544,0.075736,0.362010,0.073807,0.22138,-0.114700,11.37600,2.748900,0.23629,1.265100,0.19102,1615.10,0.18746,0.005662,16.613,0.948040,0.184820,16961.00,-0.060838,0.000130,0.488130,0.000000,0.000000,0.00000,3.06210,3.95540,-0.53449,-9.3020,11.2070,20.132,12.3,13568.0,14.5290,21.5,33.768,2.0,22.0,100.000,100.00,100.000,17.125,14.5,-7.0,0.436380,4,41,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
3668,0.482410,1.9615,0.216440,0.20095,0.21642,0.203590,0.189870,1.93820,1.000100,0.270870,0.213610,0.38734,1.920000e+07,0.799050,0.25149,2.63990,0.940730,14.4280,0.018249,0.000000,0.092416,0.55872,2.7304,0.992440,0.19747,443.840,18.360,1.13980,0.066060,0.003484,0.38274,0.010072,1.76850,0.98267,1907.8000,136.370,0.558780,0.004359,0.084325,0.241230,0.079261,0.27085,0.137280,10.08100,2.730700,0.23762,1.077100,0.25152,1638.50,0.24713,0.007563,16.829,0.942850,0.214780,20689.00,0.064229,0.000113,0.144840,0.000000,0.000000,0.00000,-7.71400,-11.82400,-25.73600,-21.4110,46.8440,30.046,12.2,26059.0,3.8523,30.5,-10.665,0.0,28.0,91.500,130.50,132.400,20.000,14.5,-16.0,0.438020,5,42,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
3669,0.500770,1.7099,0.207970,0.26136,0.21399,0.193670,0.183890,1.68980,0.971860,0.281560,0.210970,0.44290,2.030000e+07,0.738640,0.35384,1.49010,0.905010,39.0520,0.007451,0.000000,0.028768,0.48316,2.9064,0.982420,0.25902,475.560,18.469,1.16370,0.115120,0.002343,0.43769,0.022285,2.04530,0.99104,2221.2000,241.600,0.469560,0.003172,0.034821,0.102630,0.073630,0.28971,0.071485,10.03200,2.824600,0.24895,0.795720,0.35392,1689.00,0.35067,0.017581,16.927,0.907060,0.210230,34012.00,0.034509,0.000096,0.035889,0.000000,0.000000,0.00000,-0.32511,-0.71099,-3.06590,-17.8990,107.7100,38.823,10.4,31839.0,-25.8410,34.7,36.030,2.0,32.0,87.100,175.90,178.100,20.000,14.5,-20.2,0.482410,6,43,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
3670,0.611030,1.5590,0.185450,0.30728,0.19307,0.172140,0.170680,1.53890,0.960570,0.267720,0.203190,0.47601,1.099600e+02,0.692720,0.44358,1.38370,0.891630,39.6790,0.021239,0.008109,0.069562,0.40559,2.5221,0.985230,0.30533,457.060,18.543,1.13120,0.077785,0.001942,0.46988,0.023538,2.43380,0.99368,2685.8000,260.160,0.389600,0.002803,0.110010,-0.027616,0.076549,0.27871,-0.038907,9.04940,2.422700,0.24639,0.603540,0.44367,1707.30,0.44077,0.014773,16.899,0.894050,0.190210,35901.00,-0.019839,0.000072,0.120520,-0.001503,-0.007784,0.00000,3.21480,1.57190,7.15620,-4.5408,-20.8610,22.334,10.6,32801.0,-58.1220,15.6,22.571,2.0,30.0,92.900,203.20,204.500,22.000,22.0,6.4,0.500770,7,44,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
3671,0.518650,1.6148,0.176760,0.36369,0.18442,0.169550,0.197860,1.58420,0.958450,0.277780,0.213850,0.51969,1.542500e+01,0.636310,0.57156,0.42332,0.919350,15.0160,0.013783,0.059602,0.042826,0.35486,2.0440,0.994000,0.32184,505.040,18.691,0.93207,0.159350,0.041852,0.50985,0.006937,2.76460,0.88492,2500.8000,850.420,0.340120,0.065773,0.074738,0.107420,0.090225,0.28982,0.104980,7.05250,1.959100,0.31095,0.486010,0.57173,1818.10,0.50578,0.006004,17.001,0.922070,0.183310,28173.00,0.049872,0.000074,0.366480,0.001826,0.009902,0.00000,-1.58630,-7.50460,12.14500,-20.2290,28.2860,30.023,11.0,34501.0,-32.2090,11.9,13.871,1.0,29.0,91.700,227.50,214.500,21.000,20.5,8.6,0.611030,8,45,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [27]:
print("Non-numeric columns:", len(data.select_dtypes('bool').columns))

Non-numeric columns: 0

#### Splitting and Scaling

In [29]:
y = data['Financial Distress'].copy()
X = data.drop('Financial Distress', axis=1).copy()

In [30]:
scaler = StandardScaler()

X = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)

In [31]:
X

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22,x23,x24,x25,x26,x27,x28,x29,x30,x31,x32,x33,x34,x35,x36,x37,x38,x39,x40,x41,x42,x43,x44,x45,x46,x47,x48,x49,x50,x51,x52,x53,x54,x55,x56,x57,x58,x59,x60,x61,x62,x63,x64,x65,x66,x67,x68,x69,x70,x71,x72,x73,x74,x75,x76,x77,x78,x79,x81,x82,x83,x80_1,x80_2,x80_3,x80_4,x80_5,x80_6,x80_7,x80_8,x80_9,x80_10,x80_11,x80_12,x80_13,x80_14,x80_15,x80_16,x80_17,x80_18,x80_19,x80_20,x80_21,x80_22,x80_23,x80_24,x80_25,x80_26,x80_27,x80_28,x80_29,x80_30,x80_31,x80_32,x80_33,x80_34,x80_35,x80_36,x80_37
0,-0.073530,-0.889790,1.454750,0.608946,-0.752754,0.387378,-0.250547,-0.009118,-0.432897,-0.934185,1.086290,-0.085334,-1.454746,1.906736,-0.075294,0.020374,-0.034147,-0.509434,-0.023809,-0.332196,-0.033413,-0.020418,-0.727524,0.755475,-0.428698,-0.401033,0.017638,-0.555310,1.300719,-0.017779,-0.043273,-0.036348,-0.689830,-0.037430,-0.029434,-0.724567,2.614855,-0.036025,-0.023447,-0.718439,2.090481,-0.081426,-0.077343,-0.053812,1.768365,-0.382781,-0.032554,-0.447221,1.486615,0.727524,-0.052423,0.017625,-0.202875,-0.221706,-1.416965,1.669982,-0.035781,0.377138,0.023668,1.187823,1.129337,1.715153,0.225593,1.507739,0.068753,0.299540,1.407482,-0.786378,3.534495,-0.289814,2.140824,1.413550,1.505876,-0.083982,-1.003137,-0.979380,-0.873022,0.283316,0.349666,-0.390080,1.783244,1.163525,-0.061865,-0.072119,-0.061865,-0.143412,-0.043703,-0.061865,-0.05726,-0.081111,-0.316843,-0.129972,-0.093761,-0.148281,-0.033023,-0.262077,-0.340748,-0.028595,-0.144398,-0.267378,-0.219646,-0.170728,-0.18301,4.731652,-0.175731,-0.086066,-0.335246,-0.283964,-0.113866,-0.113866,-0.32969,-0.203486,-0.070186,-0.134241,-0.033023,-0.033023,-0.028595,-0.028595,-0.061865
1,-0.081102,-1.027125,1.151905,0.239109,-1.353457,0.353036,-0.155933,-0.009121,-0.857064,-0.967675,1.053115,-0.085336,-1.151901,0.899493,-0.075303,0.020321,-0.034143,-0.304622,-0.023808,-0.272289,-0.278310,-0.030365,-1.269117,0.758380,-0.525560,-0.254792,0.017447,0.220055,0.715636,0.367973,-0.043273,-0.036336,-0.327936,-0.037430,-0.029426,-0.789500,1.042020,-0.035996,-0.023440,-0.661958,0.806478,-0.074961,-0.075022,-0.056096,1.125718,-0.408567,-0.032608,-0.485617,0.746000,1.269095,-0.027441,0.017574,-1.160267,-0.218917,-1.158227,1.062175,-0.025660,0.377138,0.023668,-1.271793,1.203914,0.524792,1.490443,1.580627,2.122914,-0.345253,0.357865,-0.753320,-0.219007,-0.317911,0.071650,-1.309399,1.505876,1.212300,-0.937551,-0.915781,-0.382796,0.283316,0.374081,-0.408740,1.888901,1.236450,-0.061865,-0.072119,-0.061865,-0.143412,-0.043703,-0.061865,-0.05726,-0.081111,-0.316843,-0.129972,-0.093761,-0.148281,-0.033023,-0.262077,-0.340748,-0.028595,-0.144398,-0.267378,-0.219646,-0.170728,-0.18301,4.731652,-0.175731,-0.086066,-0.335246,-0.283964,-0.113866,-0.113866,-0.32969,-0.203486,-0.070186,-0.134241,-0.033023,-0.033023,-0.028595,-0.028595,-0.061865
2,-0.230545,-1.575751,1.723920,-0.242885,-1.076758,-0.293797,-0.339742,-0.009142,-3.172636,-1.371528,1.259197,-0.085335,-1.723927,3.976334,-0.075314,0.020356,-0.034160,-0.634398,-0.023796,-0.385951,-0.653687,-0.031134,-1.215399,1.732868,-0.820032,-0.039150,0.019696,0.748603,-0.102199,0.072683,-0.043273,-0.036328,0.401324,-0.037445,-0.029406,-1.040730,1.276509,-0.036020,-0.023443,-0.853042,1.997969,-1.011899,-0.079017,-0.066830,0.561481,-0.510026,-0.032446,-0.626133,4.074419,1.215399,-0.011544,0.017609,-1.227391,-0.216811,-2.419100,1.794589,-0.037989,0.519644,0.023686,-1.271793,0.240321,0.512754,-0.016645,0.860280,-0.575431,0.325247,-1.216560,-0.711005,-0.098029,-0.374103,-0.145884,-1.309399,1.236625,2.037255,-0.863921,-0.836842,-0.382796,-0.070258,0.300835,-0.583737,1.994557,1.309375,-0.061865,-0.072119,-0.061865,-0.143412,-0.043703,-0.061865,-0.05726,-0.081111,-0.316843,-0.129972,-0.093761,-0.148281,-0.033023,-0.262077,-0.340748,-0.028595,-0.144398,-0.267378,-0.219646,-0.170728,-0.18301,4.731652,-0.175731,-0.086066,-0.335246,-0.283964,-0.113866,-0.113866,-0.32969,-0.203486,-0.070186,-0.134241,-0.033023,-0.033023,-0.028595,-0.028595,-0.061865
3,-0.189106,-1.207824,1.366713,-0.102155,-0.631868,-0.074498,-0.105055,-0.009127,-1.272858,-1.450630,1.272418,-0.085335,-1.366709,1.534668,-0.075322,0.020409,-0.034149,-0.656305,-0.023788,-0.387821,-0.563461,-0.027339,-0.865181,1.494494,-0.588177,0.010424,0.018149,-0.415594,-0.317852,1.106022,-0.043274,-0.036311,0.524892,-0.037433,-0.029374,-0.872877,0.141362,-0.036027,-0.023409,-0.858398,0.848654,0.020628,-0.074367,-0.059470,0.648843,-0.444517,-0.032575,-0.608407,1.654491,0.865181,0.093493,0.017664,-0.814106,-0.207587,1.337856,0.762561,-0.037207,0.378516,0.023668,-1.271793,0.624529,0.928229,0.084879,-0.063836,-1.222088,0.982568,0.042980,-0.681528,-0.413881,-1.048413,1.353072,1.413550,0.698123,-1.917741,-0.806224,-0.788598,-0.300928,0.283316,1.008882,-0.534764,2.100214,1.382300,-0.061865,-0.072119,-0.061865,-0.143412,-0.043703,-0.061865,-0.05726,-0.081111,-0.316843,-0.129972,-0.093761,-0.148281,-0.033023,-0.262077,-0.340748,-0.028595,-0.144398,-0.267378,-0.219646,-0.170728,-0.18301,4.731652,-0.175731,-0.086066,-0.335246,-0.283964,-0.113866,-0.113866,-0.32969,-0.203486,-0.070186,-0.134241,-0.033023,-0.033023,-0.028595,-0.028595,-0.061865
4,-0.224075,-0.189054,1.117781,-0.056358,0.360413,-0.279855,-0.040670,-0.009093,0.706872,-0.303597,0.874712,-0.085333,-1.117777,0.822673,-0.075322,0.020527,-0.034133,-0.761802,-0.023793,-0.411799,-0.438339,-0.041582,-0.042162,1.291254,0.234366,-1.061594,0.019955,1.462942,-0.395192,1.258530,-0.043273,-0.036311,0.563334,-0.037410,-0.029372,-0.370062,-0.117102,-0.036041,-0.023380,-0.454321,0.462945,-0.037838,-0.076851,-0.046489,0.142079,-0.235088,-0.032612,-0.006390,0.931917,0.042162,-0.870575,0.017781,0.115764,-0.214402,-0.162768,-0.250164,0.007881,0.283361,0.023658,1.263705,1.129337,1.715153,0.225593,1.507739,0.068753,0.299540,1.407482,-0.786378,3.534495,-0.289814,2.140824,1.413550,1.505876,-0.083982,-1.003137,-0.979380,-0.873022,0.283316,0.349666,0.056448,-0.646859,-0.440828,-0.061865,-0.072119,-0.061865,-0.143412,-0.043703,-0.061865,-0.05726,-0.081111,-0.316843,-0.129972,-0.093761,-0.148281,-0.033023,-0.262077,-0.340748,-0.028595,-0.144398,-0.267378,-0.219646,-0.170728,-0.18301,-0.211343,-0.175731,-0.086066,-0.335246,-0.283964,-0.113866,-0.113866,3.03315,-0.203486,-0.070186,-0.134241,-0.033023,-0.033023,-0.028595,-0.028595,-0.061865
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3667,0.600718,0.609885,-2.560149,-1.193060,0.168319,0.435496,1.392953,-0.008869,-0.262853,0.651971,-1.401452,10.473196,2.560146,-0.945447,-0.075226,0.021102,-0.034049,-0.601736,-0.023817,-0.063031,-0.957329,-0.051387,4.213275,-2.053874,-0.332394,3.103162,0.016477,-0.735586,-0.867678,-0.028325,-0.043274,-0.036195,0.840599,-0.018705,-0.029455,1.119085,-0.611792,-0.035881,-0.023378,-1.007839,-0.882509,-0.037930,-0.001105,-0.009808,0.113906,1.357236,-0.032705,-0.296850,-0.896880,-4.213264,2.091464,0.018358,-0.172755,0.938358,-0.164537,-1.696333,-0.021026,0.377138,0.023668,-1.271793,0.093665,0.071776,-0.209883,-0.697887,-0.466864,-1.320170,0.882674,-0.230095,-0.071450,0.510928,0.586967,0.052075,-2.263638,0.787849,0.124977,0.169164,-0.321518,-0.247045,-0.529289,-0.249068,-0.963829,0.580124,-0.061865,-0.072119,-0.061865,-0.143412,-0.043703,-0.061865,-0.05726,-0.081111,-0.316843,-0.129972,-0.093761,-0.148281,-0.033023,-0.262077,-0.340748,-0.028595,-0.144398,-0.267378,-0.219646,-0.170728,-0.18301,-0.211343,-0.175731,-0.086066,-0.335246,-0.283964,-0.113866,-0.113866,-0.32969,-0.203486,-0.070186,-0.134241,-0.033023,-0.033023,-0.028595,-0.028595,16.164335
3668,0.394899,0.722805,-2.332018,-1.139656,0.389479,0.394978,1.116795,-0.008890,-0.178395,0.556619,-1.245281,12.993619,2.332015,-0.920003,-0.075313,0.021097,-0.033944,-0.509787,-0.023817,-0.050143,-0.919851,-0.050454,4.202173,-1.834246,-0.302993,3.142820,0.016520,-0.477562,-0.862221,0.163555,-0.043274,-0.036206,0.849339,-0.012467,-0.029409,1.080245,-0.610175,-0.035860,-0.023401,-0.978333,-0.866985,-0.020296,-0.010607,-0.010119,0.115646,1.093187,-0.032704,-0.288857,-0.869277,-4.202158,2.214101,0.018354,0.057446,1.196532,0.135700,-1.696450,-0.034418,0.377138,0.023668,-1.271793,-2.653875,-2.197820,-3.094391,-1.680735,0.345901,0.292869,0.777712,1.015923,-0.181316,1.775259,-1.904825,-1.309399,-0.648132,0.278987,0.596765,0.672734,1.087883,-0.247045,-1.627982,-0.248453,-0.858173,0.653049,-0.061865,-0.072119,-0.061865,-0.143412,-0.043703,-0.061865,-0.05726,-0.081111,-0.316843,-0.129972,-0.093761,-0.148281,-0.033023,-0.262077,-0.340748,-0.028595,-0.144398,-0.267378,-0.219646,-0.170728,-0.18301,-0.211343,-0.175731,-0.086066,-0.335246,-0.283964,-0.113866,-0.113866,-0.32969,-0.203486,-0.070186,-0.134241,-0.033023,-0.033023,-0.028595,-0.028595,16.164335
3669,0.221707,0.652220,-1.992406,-1.143906,0.310047,0.366573,0.876438,-0.008897,-0.147507,0.537621,-0.970175,13.742934,1.992405,-0.876944,-0.075323,0.021068,-0.033535,-0.747760,-0.023817,-0.325685,-0.997863,-0.049679,4.143628,-1.496883,-0.285587,3.210363,0.016525,-0.305939,-0.874487,0.485503,-0.043274,-0.036180,0.908814,-0.008361,-0.029364,0.777599,-0.612530,-0.035978,-0.023429,-1.008797,-0.861066,-0.024900,-0.010966,-0.008511,0.130472,0.697986,-0.032701,-0.271606,-0.821379,-4.143623,2.269742,0.018324,0.022485,2.119188,0.064354,-1.696573,-0.038668,0.377138,0.023668,-1.271793,-0.769959,-0.599404,-0.499622,-1.395678,1.734059,1.720915,-1.111599,1.592496,-0.486870,2.365280,0.713819,0.052075,0.428872,0.015576,1.299033,1.383016,1.087883,-0.247045,-2.140706,-0.231805,-0.752516,0.725974,-0.061865,-0.072119,-0.061865,-0.143412,-0.043703,-0.061865,-0.05726,-0.081111,-0.316843,-0.129972,-0.093761,-0.148281,-0.033023,-0.262077,-0.340748,-0.028595,-0.144398,-0.267378,-0.219646,-0.170728,-0.18301,-0.211343,-0.175731,-0.086066,-0.335246,-0.283964,-0.113866,-0.113866,-0.32969,-0.203486,-0.070186,-0.134241,-0.033023,-0.033023,-0.028595,-0.028595,16.164335
3670,0.117834,0.464548,-1.734255,-1.180487,0.137651,0.303826,0.730425,-0.008900,-0.187497,0.481633,-0.806230,-0.085261,1.734254,-0.839191,-0.075324,0.021057,-0.033525,-0.443889,-0.023815,-0.149082,-1.077950,-0.051371,4.160047,-1.243052,-0.295738,3.256218,0.016518,-0.436545,-0.878801,0.674102,-0.043274,-0.036143,0.927573,-0.002273,-0.029356,0.506364,-0.613262,-0.035799,-0.023454,-0.993005,-0.864518,-0.032626,-0.018176,-0.015396,0.127122,0.428066,-0.032699,-0.265355,-0.779700,-4.160030,2.253845,0.018313,-0.131341,2.250007,-0.066115,-1.696747,-0.035367,0.320563,0.023641,-1.271793,0.132598,-0.271049,0.670376,-0.311435,-1.198232,-0.961898,-0.901675,1.688459,-0.819052,-0.317911,-0.040958,0.052075,-0.109630,0.362799,1.721322,1.793332,2.068336,2.404759,1.106544,-0.224919,-0.646859,0.798899,-0.061865,-0.072119,-0.061865,-0.143412,-0.043703,-0.061865,-0.05726,-0.081111,-0.316843,-0.129972,-0.093761,-0.148281,-0.033023,-0.262077,-0.340748,-0.028595,-0.144398,-0.267378,-0.219646,-0.170728,-0.18301,-0.211343,-0.175731,-0.086066,-0.335246,-0.283964,-0.113866,-0.113866,-0.32969,-0.203486,-0.070186,-0.134241,-0.033023,-0.033023,-0.028595,-0.028595,16.164335
3671,0.156244,0.392129,-1.417131,-1.195613,0.116912,0.432931,0.774258,-0.008900,-0.158429,0.558347,-0.589947,-0.085325,1.417130,-0.785349,-0.075333,0.021079,-0.033934,-0.608215,-0.023799,-0.264826,-1.130326,-0.053475,4.211288,-1.152559,-0.269410,3.347929,0.016476,-0.151212,-0.449560,0.908284,-0.043274,-0.036111,0.154755,-0.004697,-0.029104,0.338521,-0.488393,-0.035883,-0.023428,-0.919017,-0.861032,-0.022556,-0.032828,-0.023337,0.211605,0.262994,-0.032697,-0.227506,-0.749626,-4.211264,2.311757,0.018337,-0.184357,1.714821,0.101234,-1.696734,-0.025772,0.445884,0.023702,-1.271793,-1.091519,-1.576549,1.241383,-1.584796,-0.077347,0.289127,-0.481828,1.858039,-0.552399,-0.837691,-0.528852,-0.628662,-0.378881,0.290960,2.097205,1.948755,1.578110,1.874399,1.375113,-0.183567,-0.541203,0.871825,-0.061865,-0.072119,-0.061865,-0.143412,-0.043703,-0.061865,-0.05726,-0.081111,-0.316843,-0.129972,-0.093761,-0.148281,-0.033023,-0.262077,-0.340748,-0.028595,-0.144398,-0.267378,-0.219646,-0.170728,-0.18301,-0.211343,-0.175731,-0.086066,-0.335246,-0.283964,-0.113866,-0.113866,-0.32969,-0.203486,-0.070186,-0.134241,-0.033023,-0.033023,-0.028595,-0.028595,16.164335

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=100)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=100)

In [33]:
dtrain = xgb.DMatrix(X_train, label=y_train)
dval = xgb.DMatrix(X_val, label=y_val)
dtest = xgb.DMatrix(X_test, label=y_test)

#### Linear Regression

In [34]:
lin_model = LinearRegression()
lin_model.fit(X_train, y_train)

print("Linear Regression R^2 Score:", lin_model.score(X_test, y_test))

Linear Regression R^2 Score: -1620.6397886601924

#### Gradient Boosting Model

In [40]:
params = {
    'learning_rate': 0.001,
    'max_depth' : 6,
    'lambda': 0.01
}

boosted_model = xgb.train(
    params,
    dtrain,
    num_boost_round = 10000,
    evals = [(dval, 'eval')],
    early_stopping_rounds=10
)

[0]	eval-rmse:1.63438
[1]	eval-rmse:1.63368
[2]	eval-rmse:1.63297
[3]	eval-rmse:1.63227
[4]	eval-rmse:1.63157
[5]	eval-rmse:1.63085
[6]	eval-rmse:1.63013
[7]	eval-rmse:1.62942
[8]	eval-rmse:1.62870
[9]	eval-rmse:1.62801
[10]	eval-rmse:1.62731
[11]	eval-rmse:1.62663
[12]	eval-rmse:1.62591
[13]	eval-rmse:1.62523
[14]	eval-rmse:1.62454
[15]	eval-rmse:1.62386
[16]	eval-rmse:1.62317
[17]	eval-rmse:1.62250
[18]	eval-rmse:1.62181
[19]	eval-rmse:1.62112
[20]	eval-rmse:1.62044
[21]	eval-rmse:1.61975
[22]	eval-rmse:1.61908
[23]	eval-rmse:1.61840
[24]	eval-rmse:1.61773
[25]	eval-rmse:1.61704
[26]	eval-rmse:1.61639
[27]	eval-rmse:1.61573
[28]	eval-rmse:1.61505
[29]	eval-rmse:1.61438
[30]	eval-rmse:1.61371
[31]	eval-rmse:1.61304
[32]	eval-rmse:1.61238
[33]	eval-rmse:1.61172
[34]	eval-rmse:1.61105
[35]	eval-rmse:1.61040
[36]	eval-rmse:1.60974
[37]	eval-rmse:1.60908
[38]	eval-rmse:1.60842
[39]	eval-rmse:1.60777
[40]	eval-rmse:1.60711
[41]	eval-rmse:1.60646
[42]	eval-rmse:1.60581
[43]	eval-rmse:1.60517
[44]	eval-rmse:1.60451
[45]	eval-rmse:1.60388
[46]	eval-rmse:1.60323
[47]	eval-rmse:1.60258
[48]	eval-rmse:1.60194
[49]	eval-rmse:1.60131
[50]	eval-rmse:1.60066
[51]	eval-rmse:1.60003
[52]	eval-rmse:1.59939
[53]	eval-rmse:1.59876
[54]	eval-rmse:1.59811
[55]	eval-rmse:1.59748
[56]	eval-rmse:1.59686
[57]	eval-rmse:1.59623
[58]	eval-rmse:1.59559
[59]	eval-rmse:1.59498
[60]	eval-rmse:1.59435
[61]	eval-rmse:1.59373
[62]	eval-rmse:1.59311
[63]	eval-rmse:1.59249
[64]	eval-rmse:1.59186
[65]	eval-rmse:1.59124
[66]	eval-rmse:1.59062
[67]	eval-rmse:1.59000
[68]	eval-rmse:1.58937
[69]	eval-rmse:1.58875
[70]	eval-rmse:1.58813
[71]	eval-rmse:1.58752
[72]	eval-rmse:1.58693
[73]	eval-rmse:1.58632
[74]	eval-rmse:1.58571
[75]	eval-rmse:1.58510
[76]	eval-rmse:1.58449
[77]	eval-rmse:1.58389
[78]	eval-rmse:1.58328
[79]	eval-rmse:1.58268
[80]	eval-rmse:1.58209
[81]	eval-rmse:1.58150
[82]	eval-rmse:1.58091
[83]	eval-rmse:1.58030
[84]	eval-rmse:1.57970
[85]	eval-rmse:1.57911
[86]	eval-rmse:1.57854
[87]	eval-rmse:1.57793
[88]	eval-rmse:1.57735
[89]	eval-rmse:1.57671
[90]	eval-rmse:1.57612
[91]	eval-rmse:1.57551
[92]	eval-rmse:1.57492
[93]	eval-rmse:1.57429
[94]	eval-rmse:1.57373
[95]	eval-rmse:1.57310
[96]	eval-rmse:1.57250
[97]	eval-rmse:1.57186
[98]	eval-rmse:1.57127
[99]	eval-rmse:1.57065
[100]	eval-rmse:1.57006
[101]	eval-rmse:1.56942
[102]	eval-rmse:1.56887
[103]	eval-rmse:1.56824
[104]	eval-rmse:1.56766
[105]	eval-rmse:1.56704
[106]	eval-rmse:1.56648
[107]	eval-rmse:1.56586
[108]	eval-rmse:1.56527
[109]	eval-rmse:1.56468
[110]	eval-rmse:1.56409
[111]	eval-rmse:1.56348
[112]	eval-rmse:1.56292
[113]	eval-rmse:1.56231
[114]	eval-rmse:1.56173
[115]	eval-rmse:1.56113
[116]	eval-rmse:1.56058
[117]	eval-rmse:1.55996
[118]	eval-rmse:1.55939
[119]	eval-rmse:1.55882
[120]	eval-rmse:1.55824
[121]	eval-rmse:1.55764
[122]	eval-rmse:1.55707
[123]	eval-rmse:1.55650
[124]	eval-rmse:1.55593
[125]	eval-rmse:1.55534
[126]	eval-rmse:1.55476
[127]	eval-rmse:1.55420
[128]	eval-rmse:1.55363
[129]	eval-rmse:1.55306
[130]	eval-rmse:1.55251
[131]	eval-rmse:1.55192
[132]	eval-rmse:1.55136
[133]	eval-rmse:1.55082
[134]	eval-rmse:1.55026
[135]	eval-rmse:1.54970
[136]	eval-rmse:1.54913
[137]	eval-rmse:1.54858
[138]	eval-rmse:1.54801
[139]	eval-rmse:1.54747
[140]	eval-rmse:1.54692
[141]	eval-rmse:1.54637
[142]	eval-rmse:1.54581
[143]	eval-rmse:1.54525
[144]	eval-rmse:1.54473
[145]	eval-rmse:1.54418
[146]	eval-rmse:1.54362
[147]	eval-rmse:1.54309
[148]	eval-rmse:1.54254
[149]	eval-rmse:1.54201
[150]	eval-rmse:1.54146
[151]	eval-rmse:1.54093
[152]	eval-rmse:1.54039
[153]	eval-rmse:1.53985
[154]	eval-rmse:1.53931
[155]	eval-rmse:1.53879
[156]	eval-rmse:1.53825
[157]	eval-rmse:1.53772
[158]	eval-rmse:1.53718
[159]	eval-rmse:1.53668
[160]	eval-rmse:1.53613
[161]	eval-rmse:1.53560
[162]	eval-rmse:1.53507
[163]	eval-rmse:1.53457
[164]	eval-rmse:1.53404
[165]	eval-rmse:1.53353
[166]	eval-rmse:1.53301
[167]	eval-rmse:1.53250
[168]	eval-rmse:1.53199
[169]	eval-rmse:1.53149
[170]	eval-rmse:1.53096
[171]	eval-rmse:1.53046
[172]	eval-rmse:1.52994
[173]	eval-rmse:1.52942
[174]	eval-rmse:1.52889
[175]	eval-rmse:1.52836
[176]	eval-rmse:1.52784
[177]	eval-rmse:1.52732
[178]	eval-rmse:1.52680
[179]	eval-rmse:1.52627
[180]	eval-rmse:1.52577
[181]	eval-rmse:1.52525
[182]	eval-rmse:1.52472
[183]	eval-rmse:1.52421
[184]	eval-rmse:1.52368
[185]	eval-rmse:1.52316
[186]	eval-rmse:1.52263
[187]	eval-rmse:1.52213
[188]	eval-rmse:1.52161
[189]	eval-rmse:1.52109
[190]	eval-rmse:1.52059
[191]	eval-rmse:1.52007
[192]	eval-rmse:1.51957
[193]	eval-rmse:1.51904
[194]	eval-rmse:1.51853
[195]	eval-rmse:1.51801
[196]	eval-rmse:1.51751
[197]	eval-rmse:1.51702
[198]	eval-rmse:1.51650
[199]	eval-rmse:1.51600
[200]	eval-rmse:1.51549
[201]	eval-rmse:1.51498
[202]	eval-rmse:1.51448
[203]	eval-rmse:1.51398
[204]	eval-rmse:1.51350
[205]	eval-rmse:1.51299
[206]	eval-rmse:1.51250
[207]	eval-rmse:1.51199
[208]	eval-rmse:1.51150
[209]	eval-rmse:1.51100
[210]	eval-rmse:1.51050
[211]	eval-rmse:1.51001
[212]	eval-rmse:1.50954
[213]	eval-rmse:1.50904
[214]	eval-rmse:1.50855
[215]	eval-rmse:1.50806
[216]	eval-rmse:1.50757
[217]	eval-rmse:1.50707
[218]	eval-rmse:1.50661
[219]	eval-rmse:1.50611
[220]	eval-rmse:1.50562
[221]	eval-rmse:1.50516
[222]	eval-rmse:1.50466
[223]	eval-rmse:1.50419
[224]	eval-rmse:1.50370
[225]	eval-rmse:1.50323
[226]	eval-rmse:1.50274
[227]	eval-rmse:1.50227
[228]	eval-rmse:1.50181
[229]	eval-rmse:1.50133
[230]	eval-rmse:1.50086
[231]	eval-rmse:1.50038
[232]	eval-rmse:1.49993
[233]	eval-rmse:1.49945
[234]	eval-rmse:1.49900
[235]	eval-rmse:1.49856
[236]	eval-rmse:1.49810
[237]	eval-rmse:1.49766
[238]	eval-rmse:1.49718
[239]	eval-rmse:1.49674
[240]	eval-rmse:1.49629
[241]	eval-rmse:1.49584
[242]	eval-rmse:1.49540
[243]	eval-rmse:1.49496
[244]	eval-rmse:1.49451
[245]	eval-rmse:1.49419
[246]	eval-rmse:1.49373
[247]	eval-rmse:1.49329
[248]	eval-rmse:1.49283
[249]	eval-rmse:1.49240
[250]	eval-rmse:1.49196
[251]	eval-rmse:1.49152
[252]	eval-rmse:1.49120
[253]	eval-rmse:1.49076
[254]	eval-rmse:1.49031
[255]	eval-rmse:1.48988
[256]	eval-rmse:1.48945
[257]	eval-rmse:1.48894
[258]	eval-rmse:1.48850
[259]	eval-rmse:1.48808
[260]	eval-rmse:1.48754
[261]	eval-rmse:1.48710
[262]	eval-rmse:1.48655
[263]	eval-rmse:1.48601
[264]	eval-rmse:1.48549
[265]	eval-rmse:1.48507
[266]	eval-rmse:1.48452
[267]	eval-rmse:1.48401
[268]	eval-rmse:1.48350
[269]	eval-rmse:1.48309
[270]	eval-rmse:1.48258
[271]	eval-rmse:1.48207
[272]	eval-rmse:1.48163
[273]	eval-rmse:1.48110
[274]	eval-rmse:1.48061
[275]	eval-rmse:1.48006
[276]	eval-rmse:1.47967
[277]	eval-rmse:1.47930
[278]	eval-rmse:1.47879
[279]	eval-rmse:1.47830
[280]	eval-rmse:1.47780
[281]	eval-rmse:1.47738
[282]	eval-rmse:1.47685
[283]	eval-rmse:1.47636
[284]	eval-rmse:1.47587
[285]	eval-rmse:1.47557
[286]	eval-rmse:1.47506
[287]	eval-rmse:1.47455
[288]	eval-rmse:1.47407
[289]	eval-rmse:1.47359
[290]	eval-rmse:1.47310
[291]	eval-rmse:1.47258
[292]	eval-rmse:1.47224
[293]	eval-rmse:1.47184
[294]	eval-rmse:1.47136
[295]	eval-rmse:1.47084
[296]	eval-rmse:1.47035
[297]	eval-rmse:1.46985
[298]	eval-rmse:1.46936
[299]	eval-rmse:1.46889
[300]	eval-rmse:1.46837
[301]	eval-rmse:1.46802
[302]	eval-rmse:1.46754
[303]	eval-rmse:1.46704
[304]	eval-rmse:1.46654
[305]	eval-rmse:1.46619
[306]	eval-rmse:1.46570
[307]	eval-rmse:1.46523
[308]	eval-rmse:1.46475
[309]	eval-rmse:1.46424
[310]	eval-rmse:1.46375
[311]	eval-rmse:1.46341
[312]	eval-rmse:1.46297
[313]	eval-rmse:1.46246
[314]	eval-rmse:1.46198
[315]	eval-rmse:1.46150
[316]	eval-rmse:1.46104
[317]	eval-rmse:1.46055
[318]	eval-rmse:1.46005
[319]	eval-rmse:1.45970
[320]	eval-rmse:1.45922
[321]	eval-rmse:1.45873
[322]	eval-rmse:1.45829
[323]	eval-rmse:1.45778
[324]	eval-rmse:1.45732
[325]	eval-rmse:1.45696
[326]	eval-rmse:1.45648
[327]	eval-rmse:1.45601
[328]	eval-rmse:1.45555
[329]	eval-rmse:1.45506
[330]	eval-rmse:1.45462
[331]	eval-rmse:1.45416
[332]	eval-rmse:1.45380
[333]	eval-rmse:1.45336
[334]	eval-rmse:1.45290
[335]	eval-rmse:1.45248
[336]	eval-rmse:1.45198
[337]	eval-rmse:1.45154
[338]	eval-rmse:1.45106
[339]	eval-rmse:1.45061
[340]	eval-rmse:1.45027
[341]	eval-rmse:1.44981
[342]	eval-rmse:1.44942
[343]	eval-rmse:1.44895
[344]	eval-rmse:1.44847
[345]	eval-rmse:1.44804
[346]	eval-rmse:1.44770
[347]	eval-rmse:1.44724
[348]	eval-rmse:1.44683
[349]	eval-rmse:1.44637
[350]	eval-rmse:1.44593
[351]	eval-rmse:1.44546
[352]	eval-rmse:1.44516
[353]	eval-rmse:1.44468
[354]	eval-rmse:1.44426
[355]	eval-rmse:1.44385
[356]	eval-rmse:1.44349
[357]	eval-rmse:1.44308
[358]	eval-rmse:1.44264
[359]	eval-rmse:1.44229
[360]	eval-rmse:1.44186
[361]	eval-rmse:1.44143
[362]	eval-rmse:1.44114
[363]	eval-rmse:1.44068
[364]	eval-rmse:1.44028
[365]	eval-rmse:1.43998
[366]	eval-rmse:1.43952
[367]	eval-rmse:1.43910
[368]	eval-rmse:1.43880
[369]	eval-rmse:1.43842
[370]	eval-rmse:1.43800
[371]	eval-rmse:1.43770
[372]	eval-rmse:1.43732
[373]	eval-rmse:1.43693
[374]	eval-rmse:1.43653
[375]	eval-rmse:1.43623
[376]	eval-rmse:1.43587
[377]	eval-rmse:1.43558
[378]	eval-rmse:1.43520
[379]	eval-rmse:1.43467
[380]	eval-rmse:1.43433
[381]	eval-rmse:1.43380
[382]	eval-rmse:1.43327
[383]	eval-rmse:1.43275
[384]	eval-rmse:1.43222
[385]	eval-rmse:1.43182
[386]	eval-rmse:1.43129
[387]	eval-rmse:1.43077
[388]	eval-rmse:1.43025
[389]	eval-rmse:1.42984
[390]	eval-rmse:1.42932
[391]	eval-rmse:1.42881
[392]	eval-rmse:1.42830
[393]	eval-rmse:1.42778
[394]	eval-rmse:1.42738
[395]	eval-rmse:1.42687
[396]	eval-rmse:1.42636
[397]	eval-rmse:1.42585
[398]	eval-rmse:1.42547
[399]	eval-rmse:1.42496
[400]	eval-rmse:1.42445
[401]	eval-rmse:1.42395
[402]	eval-rmse:1.42356
[403]	eval-rmse:1.42305
[404]	eval-rmse:1.42256
[405]	eval-rmse:1.42205
[406]	eval-rmse:1.42155
[407]	eval-rmse:1.42117
[408]	eval-rmse:1.42067
[409]	eval-rmse:1.42017
[410]	eval-rmse:1.41968
[411]	eval-rmse:1.41927
[412]	eval-rmse:1.41878
[413]	eval-rmse:1.41829
[414]	eval-rmse:1.41779
[415]	eval-rmse:1.41739
[416]	eval-rmse:1.41688
[417]	eval-rmse:1.41639
[418]	eval-rmse:1.41590
[419]	eval-rmse:1.41539
[420]	eval-rmse:1.41499
[421]	eval-rmse:1.41450
[422]	eval-rmse:1.41402
[423]	eval-rmse:1.41352
[424]	eval-rmse:1.41312
[425]	eval-rmse:1.41264
[426]	eval-rmse:1.41213
[427]	eval-rmse:1.41164
[428]	eval-rmse:1.41125
[429]	eval-rmse:1.41076
[430]	eval-rmse:1.41028
[431]	eval-rmse:1.40979
[432]	eval-rmse:1.40940
[433]	eval-rmse:1.40893
[434]	eval-rmse:1.40844
[435]	eval-rmse:1.40796
[436]	eval-rmse:1.40747
[437]	eval-rmse:1.40708
[438]	eval-rmse:1.40660
[439]	eval-rmse:1.40612
[440]	eval-rmse:1.40566
[441]	eval-rmse:1.40526
[442]	eval-rmse:1.40479
[443]	eval-rmse:1.40431
[444]	eval-rmse:1.40385
[445]	eval-rmse:1.40338
[446]	eval-rmse:1.40300
[447]	eval-rmse:1.40252
[448]	eval-rmse:1.40203
[449]	eval-rmse:1.40157
[450]	eval-rmse:1.40117
[451]	eval-rmse:1.40070
[452]	eval-rmse:1.40024
[453]	eval-rmse:1.39977
[454]	eval-rmse:1.39938
[455]	eval-rmse:1.39892
[456]	eval-rmse:1.39846
[457]	eval-rmse:1.39800
[458]	eval-rmse:1.39762
[459]	eval-rmse:1.39717
[460]	eval-rmse:1.39670
[461]	eval-rmse:1.39627
[462]	eval-rmse:1.39590
[463]	eval-rmse:1.39544
[464]	eval-rmse:1.39501
[465]	eval-rmse:1.39454
[466]	eval-rmse:1.39409
[467]	eval-rmse:1.39371
[468]	eval-rmse:1.39326
[469]	eval-rmse:1.39281
[470]	eval-rmse:1.39237
[471]	eval-rmse:1.39194
[472]	eval-rmse:1.39162
[473]	eval-rmse:1.39117
[474]	eval-rmse:1.39072
[475]	eval-rmse:1.39028
[476]	eval-rmse:1.38985
[477]	eval-rmse:1.38956
[478]	eval-rmse:1.38910
[479]	eval-rmse:1.38867
[480]	eval-rmse:1.38824
[481]	eval-rmse:1.38779
[482]	eval-rmse:1.38747
[483]	eval-rmse:1.38705
[484]	eval-rmse:1.38662
[485]	eval-rmse:1.38618
[486]	eval-rmse:1.38588
[487]	eval-rmse:1.38544
[488]	eval-rmse:1.38502
[489]	eval-rmse:1.38464
[490]	eval-rmse:1.38420
[491]	eval-rmse:1.38378
[492]	eval-rmse:1.38349
[493]	eval-rmse:1.38306
[494]	eval-rmse:1.38264
[495]	eval-rmse:1.38226
[496]	eval-rmse:1.38183
[497]	eval-rmse:1.38139
[498]	eval-rmse:1.38110
[499]	eval-rmse:1.38068
[500]	eval-rmse:1.38026
[501]	eval-rmse:1.37985
[502]	eval-rmse:1.37948
[503]	eval-rmse:1.37913
[504]	eval-rmse:1.37871
[505]	eval-rmse:1.37830
[506]	eval-rmse:1.37800
[507]	eval-rmse:1.37759
[508]	eval-rmse:1.37717
[509]	eval-rmse:1.37682
[510]	eval-rmse:1.37641
[511]	eval-rmse:1.37600
[512]	eval-rmse:1.37560
[513]	eval-rmse:1.37518
[514]	eval-rmse:1.37477
[515]	eval-rmse:1.37441
[516]	eval-rmse:1.37400
[517]	eval-rmse:1.37360
[518]	eval-rmse:1.37325
[519]	eval-rmse:1.37284
[520]	eval-rmse:1.37244
[521]	eval-rmse:1.37204
[522]	eval-rmse:1.37164
[523]	eval-rmse:1.37122
[524]	eval-rmse:1.37087
[525]	eval-rmse:1.37045
[526]	eval-rmse:1.37007
[527]	eval-rmse:1.36967
[528]	eval-rmse:1.36927
[529]	eval-rmse:1.36888
[530]	eval-rmse:1.36849
[531]	eval-rmse:1.36814
[532]	eval-rmse:1.36775
[533]	eval-rmse:1.36737
[534]	eval-rmse:1.36698
[535]	eval-rmse:1.36659
[536]	eval-rmse:1.36620
[537]	eval-rmse:1.36589
[538]	eval-rmse:1.36550
[539]	eval-rmse:1.36511
[540]	eval-rmse:1.36476
[541]	eval-rmse:1.36438
[542]	eval-rmse:1.36401
[543]	eval-rmse:1.36366
[544]	eval-rmse:1.36328
[545]	eval-rmse:1.36290
[546]	eval-rmse:1.36251
[547]	eval-rmse:1.36216
[548]	eval-rmse:1.36178
[549]	eval-rmse:1.36142
[550]	eval-rmse:1.36104
[551]	eval-rmse:1.36070
[552]	eval-rmse:1.36032
[553]	eval-rmse:1.35995
[554]	eval-rmse:1.35957
[555]	eval-rmse:1.35921
[556]	eval-rmse:1.35890
[557]	eval-rmse:1.35853
[558]	eval-rmse:1.35817
[559]	eval-rmse:1.35783
[560]	eval-rmse:1.35746
[561]	eval-rmse:1.35709
[562]	eval-rmse:1.35679
[563]	eval-rmse:1.35643
[564]	eval-rmse:1.35605
[565]	eval-rmse:1.35569
[566]	eval-rmse:1.35536
[567]	eval-rmse:1.35500
[568]	eval-rmse:1.35465
[569]	eval-rmse:1.35429
[570]	eval-rmse:1.35395
[571]	eval-rmse:1.35358
[572]	eval-rmse:1.35323
[573]	eval-rmse:1.35288
[574]	eval-rmse:1.35258
[575]	eval-rmse:1.35222
[576]	eval-rmse:1.35187
[577]	eval-rmse:1.35150
[578]	eval-rmse:1.35119
[579]	eval-rmse:1.35084
[580]	eval-rmse:1.35051
[581]	eval-rmse:1.35020
[582]	eval-rmse:1.34984
[583]	eval-rmse:1.34950
[584]	eval-rmse:1.34918
[585]	eval-rmse:1.34882
[586]	eval-rmse:1.34847
[587]	eval-rmse:1.34813
[588]	eval-rmse:1.34784
[589]	eval-rmse:1.34749
[590]	eval-rmse:1.34716
[591]	eval-rmse:1.34686
[592]	eval-rmse:1.34651
[593]	eval-rmse:1.34616
[594]	eval-rmse:1.34583
[595]	eval-rmse:1.34550
[596]	eval-rmse:1.34516
[597]	eval-rmse:1.34482
[598]	eval-rmse:1.34450
[599]	eval-rmse:1.34417
[600]	eval-rmse:1.34384
[601]	eval-rmse:1.34352
[602]	eval-rmse:1.34319
[603]	eval-rmse:1.34286
[604]	eval-rmse:1.34253
[605]	eval-rmse:1.34221
[606]	eval-rmse:1.34196
[607]	eval-rmse:1.34162
[608]	eval-rmse:1.34136
[609]	eval-rmse:1.34104
[610]	eval-rmse:1.34078
[611]	eval-rmse:1.34046
[612]	eval-rmse:1.34021
[613]	eval-rmse:1.33990
[614]	eval-rmse:1.33964
[615]	eval-rmse:1.33930
[616]	eval-rmse:1.33900
[617]	eval-rmse:1.33872
[618]	eval-rmse:1.33846
[619]	eval-rmse:1.33820
[620]	eval-rmse:1.33790
[621]	eval-rmse:1.33762
[622]	eval-rmse:1.33730
[623]	eval-rmse:1.33703
[624]	eval-rmse:1.33673
[625]	eval-rmse:1.33647
[626]	eval-rmse:1.33622
[627]	eval-rmse:1.33589
[628]	eval-rmse:1.33565
[629]	eval-rmse:1.33538
[630]	eval-rmse:1.33512
[631]	eval-rmse:1.33487
[632]	eval-rmse:1.33461
[633]	eval-rmse:1.33430
[634]	eval-rmse:1.33405
[635]	eval-rmse:1.33381
[636]	eval-rmse:1.33355
[637]	eval-rmse:1.33331
[638]	eval-rmse:1.33305
[639]	eval-rmse:1.33280
[640]	eval-rmse:1.33255
[641]	eval-rmse:1.33224
[642]	eval-rmse:1.33200
[643]	eval-rmse:1.33175
[644]	eval-rmse:1.33150
[645]	eval-rmse:1.33126
[646]	eval-rmse:1.33101
[647]	eval-rmse:1.33078
[648]	eval-rmse:1.33054
[649]	eval-rmse:1.33029
[650]	eval-rmse:1.33001
[651]	eval-rmse:1.32976
[652]	eval-rmse:1.32948
[653]	eval-rmse:1.32924
[654]	eval-rmse:1.32899
[655]	eval-rmse:1.32878
[656]	eval-rmse:1.32851
[657]	eval-rmse:1.32826
[658]	eval-rmse:1.32793
[659]	eval-rmse:1.32769
[660]	eval-rmse:1.32740
[661]	eval-rmse:1.32716
[662]	eval-rmse:1.32689
[663]	eval-rmse:1.32664
[664]	eval-rmse:1.32642
[665]	eval-rmse:1.32616
[666]	eval-rmse:1.32591
[667]	eval-rmse:1.32564
[668]	eval-rmse:1.32538
[669]	eval-rmse:1.32513
[670]	eval-rmse:1.32487
[671]	eval-rmse:1.32464
[672]	eval-rmse:1.32441
[673]	eval-rmse:1.32412
[674]	eval-rmse:1.32385
[675]	eval-rmse:1.32361
[676]	eval-rmse:1.32339
[677]	eval-rmse:1.32313
[678]	eval-rmse:1.32288
[679]	eval-rmse:1.32261
[680]	eval-rmse:1.32236
[681]	eval-rmse:1.32211
[682]	eval-rmse:1.32185
[683]	eval-rmse:1.32162
[684]	eval-rmse:1.32139
[685]	eval-rmse:1.32115
[686]	eval-rmse:1.32090
[687]	eval-rmse:1.32067
[688]	eval-rmse:1.32042
[689]	eval-rmse:1.32014
[690]	eval-rmse:1.31989
[691]	eval-rmse:1.31965
[692]	eval-rmse:1.31943
[693]	eval-rmse:1.31919
[694]	eval-rmse:1.31894
[695]	eval-rmse:1.31864
[696]	eval-rmse:1.31840
[697]	eval-rmse:1.31813
[698]	eval-rmse:1.31788
[699]	eval-rmse:1.31764
[700]	eval-rmse:1.31739
[701]	eval-rmse:1.31717
[702]	eval-rmse:1.31693
[703]	eval-rmse:1.31669
[704]	eval-rmse:1.31648
[705]	eval-rmse:1.31623
[706]	eval-rmse:1.31599
[707]	eval-rmse:1.31574
[708]	eval-rmse:1.31549
[709]	eval-rmse:1.31520
[710]	eval-rmse:1.31496
[711]	eval-rmse:1.31474
[712]	eval-rmse:1.31451
[713]	eval-rmse:1.31428
[714]	eval-rmse:1.31403
[715]	eval-rmse:1.31377
[716]	eval-rmse:1.31355
[717]	eval-rmse:1.31331
[718]	eval-rmse:1.31303
[719]	eval-rmse:1.31279
[720]	eval-rmse:1.31259
[721]	eval-rmse:1.31237
[722]	eval-rmse:1.31201
[723]	eval-rmse:1.31175
[724]	eval-rmse:1.31152
[725]	eval-rmse:1.31132
[726]	eval-rmse:1.31104
[727]	eval-rmse:1.31068
[728]	eval-rmse:1.31044
[729]	eval-rmse:1.31018
[730]	eval-rmse:1.30993
[731]	eval-rmse:1.30971
[732]	eval-rmse:1.30947
[733]	eval-rmse:1.30924
[734]	eval-rmse:1.30903
[735]	eval-rmse:1.30882
[736]	eval-rmse:1.30857
[737]	eval-rmse:1.30832
[738]	eval-rmse:1.30810
[739]	eval-rmse:1.30784
[740]	eval-rmse:1.30757
[741]	eval-rmse:1.30734
[742]	eval-rmse:1.30714
[743]	eval-rmse:1.30691
[744]	eval-rmse:1.30664
[745]	eval-rmse:1.30641
[746]	eval-rmse:1.30618
[747]	eval-rmse:1.30590
[748]	eval-rmse:1.30568
[749]	eval-rmse:1.30547
[750]	eval-rmse:1.30526
[751]	eval-rmse:1.30505
[752]	eval-rmse:1.30478
[753]	eval-rmse:1.30457
[754]	eval-rmse:1.30435
[755]	eval-rmse:1.30414
[756]	eval-rmse:1.30388
[757]	eval-rmse:1.30366
[758]	eval-rmse:1.30345
[759]	eval-rmse:1.30320
[760]	eval-rmse:1.30298
[761]	eval-rmse:1.30276
[762]	eval-rmse:1.30256
[763]	eval-rmse:1.30236
[764]	eval-rmse:1.30209
[765]	eval-rmse:1.30188
[766]	eval-rmse:1.30169
[767]	eval-rmse:1.30145
[768]	eval-rmse:1.30124
[769]	eval-rmse:1.30098
[770]	eval-rmse:1.30077
[771]	eval-rmse:1.30051
[772]	eval-rmse:1.30031
[773]	eval-rmse:1.30010
[774]	eval-rmse:1.29990
[775]	eval-rmse:1.29970
[776]	eval-rmse:1.29944
[777]	eval-rmse:1.29923
[778]	eval-rmse:1.29901
[779]	eval-rmse:1.29883
[780]	eval-rmse:1.29862
[781]	eval-rmse:1.29837
[782]	eval-rmse:1.29817
[783]	eval-rmse:1.29791
[784]	eval-rmse:1.29768
[785]	eval-rmse:1.29748
[786]	eval-rmse:1.29728
[787]	eval-rmse:1.29706
[788]	eval-rmse:1.29681
[789]	eval-rmse:1.29658
[790]	eval-rmse:1.29637
[791]	eval-rmse:1.29612
[792]	eval-rmse:1.29589
[793]	eval-rmse:1.29567
[794]	eval-rmse:1.29543
[795]	eval-rmse:1.29520
[796]	eval-rmse:1.29495
[797]	eval-rmse:1.29478
[798]	eval-rmse:1.29455
[799]	eval-rmse:1.29436
[800]	eval-rmse:1.29418
[801]	eval-rmse:1.29394
[802]	eval-rmse:1.29374
[803]	eval-rmse:1.29350
[804]	eval-rmse:1.29327
[805]	eval-rmse:1.29304
[806]	eval-rmse:1.29287
[807]	eval-rmse:1.29265
[808]	eval-rmse:1.29246
[809]	eval-rmse:1.29222
[810]	eval-rmse:1.29200
[811]	eval-rmse:1.29177
[812]	eval-rmse:1.29154
[813]	eval-rmse:1.29137
[814]	eval-rmse:1.29116
[815]	eval-rmse:1.29097
[816]	eval-rmse:1.29075
[817]	eval-rmse:1.29052
[818]	eval-rmse:1.29028
[819]	eval-rmse:1.29011
[820]	eval-rmse:1.28993
[821]	eval-rmse:1.28971
[822]	eval-rmse:1.28949
[823]	eval-rmse:1.28927
[824]	eval-rmse:1.28909
[825]	eval-rmse:1.28887
[826]	eval-rmse:1.28865
[827]	eval-rmse:1.28843
[828]	eval-rmse:1.28827
[829]	eval-rmse:1.28805
[830]	eval-rmse:1.28783
[831]	eval-rmse:1.28764
[832]	eval-rmse:1.28746
[833]	eval-rmse:1.28726
[834]	eval-rmse:1.28704
[835]	eval-rmse:1.28682
[836]	eval-rmse:1.28660

In [41]:
print("XGB Model Score: {:.4f}".format(r2_score(y_test, boosted_model.predict(dtest))))

XGB Model Score: 0.0817