## BlueBerry Yield Prediction

Given *data about wild blueberries*, let's try to predict the **yield** for a given record.

We will use a random forest regression model to make our predictions.

Data source: https://www.kaggle.com/datasets/saurabhshahane/wild-blueberry-yield-prediction

### Importing Libraries

In [2]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler

from sklearn.ensemble import RandomForestRegressor

In [3]:
data = pd.read_csv('archive/WildBlueberryPollinationSimulationData.csv')
data

,Row#,clonesize,honeybee,bumbles,andrena,osmia,MaxOfUpperTRange,MinOfUpperTRange,AverageOfUpperTRange,MaxOfLowerTRange,MinOfLowerTRange,AverageOfLowerTRange,RainingDays,AverageRainingDays,fruitset,fruitmass,seeds,yield
0,0,37.5,0.750,0.250,0.250,0.250,86.0,52.0,71.9,62.0,30.0,50.8,16.00,0.26,0.410652,0.408159,31.678898,3813.165795
1,1,37.5,0.750,0.250,0.250,0.250,86.0,52.0,71.9,62.0,30.0,50.8,1.00,0.10,0.444254,0.425458,33.449385,4947.605663
2,2,37.5,0.750,0.250,0.250,0.250,94.6,57.2,79.0,68.2,33.0,55.9,16.00,0.26,0.383787,0.399172,30.546306,3866.798965
3,3,37.5,0.750,0.250,0.250,0.250,94.6,57.2,79.0,68.2,33.0,55.9,1.00,0.10,0.407564,0.408789,31.562586,4303.943030
4,4,37.5,0.750,0.250,0.250,0.250,86.0,52.0,71.9,62.0,30.0,50.8,24.00,0.39,0.354413,0.382703,28.873714,3436.493543
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
772,772,10.0,0.537,0.117,0.409,0.058,86.0,52.0,71.9,62.0,30.0,50.8,3.77,0.06,0.486815,0.428012,33.447471,5333.873335
773,773,40.0,0.537,0.117,0.409,0.058,86.0,52.0,71.9,62.0,30.0,50.8,3.77,0.06,0.342841,0.377915,28.462005,3373.436842
774,774,20.0,0.537,0.117,0.409,0.058,86.0,52.0,71.9,62.0,30.0,50.8,24.00,0.39,0.404617,0.401670,30.748240,4203.027624
775,775,20.0,0.537,0.117,0.409,0.058,89.0,39.0,65.6,66.0,28.0,45.3,3.77,0.06,0.401538,0.399935,30.582161,4166.299735
776,776,20.0,0.537,0.117,0.409,0.058,89.0,39.0,65.6,66.0,28.0,45.3,24.00,0.39,0.384646,0.392303,29.742583,3943.131681

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 777 entries, 0 to 776
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Row#                  777 non-null    int64
 1   clonesize             777 non-null    float64
 2   honeybee              777 non-null    float64
 3   bumbles               777 non-null    float64
 4   andrena               777 non-null    float64
 5   osmia                 777 non-null    float64
 6   MaxOfUpperTRange      777 non-null    float64
 7   MinOfUpperTRange      777 non-null    float64
 8   AverageOfUpperTRange  777 non-null    float64
 9   MaxOfLowerTRange      777 non-null    float64
 10  MinOfLowerTRange      777 non-null    float64
 11  AverageOfLowerTRange  777 non-null    float64
 12  RainingDays           777 non-null    float64
 13  AverageRainingDays    777 non-null    float64
 14  fruitset              777 non-null    float64
 15  fruitmass             777 non-null    float64
 16  seeds                 777 non-null    float64
 17  yield                 777 non-null    float64
dtypes: float64(17), int64(1)
memory usage: 109.4 KB

### Preprocessing

In [5]:
df = data.copy()

In [6]:
# Drop Row# column
df = df.drop('Row#', axis=1)

In [7]:
df

,clonesize,honeybee,bumbles,andrena,osmia,MaxOfUpperTRange,MinOfUpperTRange,AverageOfUpperTRange,MaxOfLowerTRange,MinOfLowerTRange,AverageOfLowerTRange,RainingDays,AverageRainingDays,fruitset,fruitmass,seeds,yield
0,37.5,0.750,0.250,0.250,0.250,86.0,52.0,71.9,62.0,30.0,50.8,16.00,0.26,0.410652,0.408159,31.678898,3813.165795
1,37.5,0.750,0.250,0.250,0.250,86.0,52.0,71.9,62.0,30.0,50.8,1.00,0.10,0.444254,0.425458,33.449385,4947.605663
2,37.5,0.750,0.250,0.250,0.250,94.6,57.2,79.0,68.2,33.0,55.9,16.00,0.26,0.383787,0.399172,30.546306,3866.798965
3,37.5,0.750,0.250,0.250,0.250,94.6,57.2,79.0,68.2,33.0,55.9,1.00,0.10,0.407564,0.408789,31.562586,4303.943030
4,37.5,0.750,0.250,0.250,0.250,86.0,52.0,71.9,62.0,30.0,50.8,24.00,0.39,0.354413,0.382703,28.873714,3436.493543
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
772,10.0,0.537,0.117,0.409,0.058,86.0,52.0,71.9,62.0,30.0,50.8,3.77,0.06,0.486815,0.428012,33.447471,5333.873335
773,40.0,0.537,0.117,0.409,0.058,86.0,52.0,71.9,62.0,30.0,50.8,3.77,0.06,0.342841,0.377915,28.462005,3373.436842
774,20.0,0.537,0.117,0.409,0.058,86.0,52.0,71.9,62.0,30.0,50.8,24.00,0.39,0.404617,0.401670,30.748240,4203.027624
775,20.0,0.537,0.117,0.409,0.058,89.0,39.0,65.6,66.0,28.0,45.3,3.77,0.06,0.401538,0.399935,30.582161,4166.299735
776,20.0,0.537,0.117,0.409,0.058,89.0,39.0,65.6,66.0,28.0,45.3,24.00,0.39,0.384646,0.392303,29.742583,3943.131681

In [8]:
# Split df into X and y
y = df['yield'].copy()
X = df.drop('yield', axis=1).copy()

In [9]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, shuffle=True, random_state=1)

In [10]:
X_train

,clonesize,honeybee,bumbles,andrena,osmia,MaxOfUpperTRange,MinOfUpperTRange,AverageOfUpperTRange,MaxOfLowerTRange,MinOfLowerTRange,AverageOfLowerTRange,RainingDays,AverageRainingDays,fruitset,fruitmass,seeds
214,12.5,0.25,0.250,0.50,0.50,94.6,57.2,79.0,68.2,33.0,55.9,1.00,0.10,0.582954,0.488176,40.559770
88,12.5,0.25,0.250,0.25,0.50,86.0,52.0,71.9,62.0,30.0,50.8,34.00,0.56,0.435969,0.419720,32.815794
479,25.0,0.50,0.250,0.38,0.63,94.6,57.2,79.0,68.2,33.0,55.9,24.00,0.39,0.364565,0.391617,29.908518
602,25.0,0.50,0.250,0.75,0.50,86.0,52.0,71.9,62.0,30.0,50.8,1.00,0.10,0.523846,0.460305,37.277297
147,12.5,0.25,0.250,0.38,0.38,86.0,52.0,71.9,62.0,30.0,50.8,16.00,0.26,0.553730,0.471250,38.534569
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,25.0,0.50,0.380,0.50,0.63,94.6,57.2,79.0,68.2,33.0,55.9,16.00,0.26,0.527592,0.464639,37.782288
767,20.0,0.00,0.585,0.00,0.00,86.0,52.0,71.9,62.0,30.0,50.8,3.77,0.06,0.599984,0.529791,46.585105
72,12.5,0.25,0.250,0.25,0.38,86.0,52.0,71.9,62.0,30.0,50.8,34.00,0.56,0.416271,0.409438,31.577558
235,12.5,0.25,0.250,0.50,0.63,77.4,46.8,64.7,55.8,27.0,45.8,16.00,0.26,0.589306,0.488616,40.546480
37,25.0,0.25,0.250,0.25,0.25,77.4,46.8,64.7,55.8,27.0,45.8,24.00,0.39,0.426065,0.420188,32.849238

In [11]:
y_train

214    7243.226111
88     4684.893205
479    3723.523376
602    6521.291119
147    6683.200614
          ...
715    6327.477365
767    7575.801245
72     4350.424670
235    7560.205645
37     4356.945873
Name: yield, Length: 543, dtype: float64

### Training

In [12]:
model = RandomForestRegressor(random_state=1)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [13]:
y_pred

array([8345.26132723, 5618.9444    , 6039.38668839, 4176.40876235,
       8476.18787475, 7235.07145337, 6225.91778631, 6857.39342066,
       6641.19758699, 6581.26822553, 5667.97933405, 5774.07179343,
       4463.30599725, 7808.5471399 , 6673.13876938, 5923.38154122,
       4533.26616863, 7442.43818375, 7824.08722453, 5234.77409655,
       6303.47870125, 3739.54412602, 7620.41284884, 5626.25439344,
       5210.03370621, 5973.59059236, 3631.64743561, 4332.7963414 ,
       5749.65569172, 4615.80085906, 6704.24045616, 3790.68113273,
       5145.19707942, 8403.1012091 , 7425.34384294, 6837.50039036,
       6752.56507517, 5670.1757635 , 5380.22263112, 8735.94512478,
       8170.00086155, 6757.664453  , 2611.7916052 , 5803.15364341,
       7106.60122994, 5407.97104794, 4684.9083185 , 5778.9663783 ,
       4337.31262934, 5837.68993924, 5044.29153508, 7561.72383212,
       7824.12933319, 7250.22104188, 3539.04528854, 6312.96062912,
       4781.34679868, 5274.78854039, 5132.81890289, 6463.66103917,
       4106.60873419, 5477.10758407, 7165.382356  , 7279.27861914,
       7144.39146465, 2738.88619342, 7186.31629007, 5883.73128874,
       4852.22708143, 7769.24442202, 6693.24701966, 3968.10521044,
       7560.91640506, 4905.57837162, 7155.80545864, 4911.64947213,
       3930.8525393 , 6224.98206786, 6010.14495547, 5923.11814951,
       6348.92569118, 6553.77332156, 6651.84725314, 3721.92876923,
       3471.60864741, 5313.93037713, 6734.10987471, 6676.19203621,
       6230.4733434 , 6465.24201919, 6042.30826483, 6473.59235316,
       4759.60367185, 6107.46592376, 4651.72927013, 5127.28409046,
       8154.8565822 , 7229.67698925, 6134.47729787, 7347.72159558,
       6544.27398503, 7193.47627144, 3287.80591582, 7409.15286549,
       6461.97324803, 6907.40411815, 4944.04704508, 5987.7896387 ,
       3703.94914292, 6448.36651422, 4051.33906469, 6751.52640465,
       4314.6706017 , 5634.05623424, 5989.15643378, 7998.15364143,
       7553.68824801, 5655.41727185, 7421.27160071, 6083.44079508,
       8486.17898537, 5201.63248852, 6735.70524959, 4374.71770848,
       3799.17352379, 6475.10670604, 6383.59085635, 5625.63196964,
       5141.58997913, 8345.000403  , 8189.83040259, 7391.07697071,
       6424.86481932, 5204.80178581, 4962.39362984, 4315.26875228,
       6333.5355801 , 5460.35370677, 5589.45660357, 5930.75949784,
       5773.51276667, 3458.18365966, 8195.43403928, 4251.18193737,
       8699.27721542, 4417.38941747, 6707.49783222, 3373.01015266,
       5819.8702858 , 4287.13560415, 7188.05755403, 7476.0755944 ,
       7422.71023859, 4439.6397203 , 6429.70018598, 7503.46674487,
       4105.73898349, 5410.51074426, 7883.97089387, 7393.08753484,
       6275.0731187 , 3715.17834142, 5260.97494726, 6701.30433097,
       6271.10273722, 6821.44565208, 7869.02887921, 6919.84920044,
       4963.84611027, 6325.53713453, 5981.11514491, 5403.88385495,
       5560.36082015, 5392.45893203, 5429.98131433, 6738.62980933,
       3488.65016061, 7535.01365593, 8479.97113544, 4936.03640061,
       7160.00787032, 4166.9246541 , 4892.79122269, 3352.97195922,
       2962.64451454, 7398.5912383 , 7605.84895385, 8158.54506561,
       6478.97211191, 6894.57883632, 6583.48003553, 4026.05808912,
       5478.92810087, 7809.07912616, 5182.35868864, 7804.24381862,
       6589.09236379, 6252.9480909 , 6041.63800752, 5006.06899654,
       5398.06706746, 6210.04450954, 3631.80350241, 5974.12073313,
       6913.30987816, 3987.725631  , 3902.91074994, 4671.15644441,
       6736.60205804, 4735.14994292, 7423.61281776, 5478.25251075,
       5793.44546737, 7561.57458665, 2633.52343075, 7377.70544112,
       7844.52604324, 5820.44003865, 6460.75178613, 6488.23071884,
       6851.33984029, 5100.80124217, 5519.64077904, 4984.78382882,
       7471.08128584, 3405.31400858, 6049.77919056, 6166.96666962,
       6870.56393123, 7482.89396447, 8479.85703076, 6646.73021235,
       3364.98680535, 4190.44874259])

In [17]:
rmse = np.sqrt(np.mean((y_test - y_pred)**2))
rmse

np.float64(186.18842159592205)

In [24]:
r2_score = 1 - (np.sum((y_test - y_pred)**2) / np.sum(((y_test - y_test.mean())**2)))
r2_score

np.float64(0.9824426326751491)

In [25]:
print("RMSE: {:.2f}".format(rmse))
print("R2 Score: {:.5f}".format(r2_score))

RMSE: 186.19
R2 Score: 0.98244

In [27]:
params = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [2, 4, 5, 8, 10]
}

model = GridSearchCV(RandomForestRegressor(random_state=1), params)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

rmse = np.sqrt(np.mean((y_test - y_pred)**2))
r2_score = 1 - (np.sum((y_test - y_pred)**2) / np.sum(((y_test - y_test.mean())**2)))

print("RMSE: {:.2f}".format(rmse))
print("R2 Score: {:.5f}".format(r2_score))

RMSE: 187.21
R2 Score: 0.98225

In [28]:
model.best_params_

{'max_depth': 10, 'n_estimators': 50}