## Automobile Price Prediction with XGBoost

Given *data about various automobiles*, let's try to predict the **price** of a given automobile.

We will use XGBoost to make our predictions.

Data source: https://www.kaggle.com/datasets/toramky/automobile-dataset

### Importing Libraries

In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import xgboost as xgb

from sklearn.metrics import r2_score

pd.set_option('display.max_columns', None)

In [2]:
data = pd.read_csv('Automobile_data.csv')
data

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5,2952,ohc,four,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,55.5,3049,ohc,four,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5,3012,ohcv,six,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5,3217,ohc,six,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5,3062,ohc,four,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    str
 2   make               205 non-null    str
 3   fuel-type          205 non-null    str
 4   aspiration         205 non-null    str
 5   num-of-doors       205 non-null    str
 6   body-style         205 non-null    str
 7   drive-wheels       205 non-null    str
 8   engine-location    205 non-null    str
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    str
 15  num-of-cylinders   205 non-null    str
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    str
 18  bore               205 non-null    str
 19  stroke             205 non-null    str
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    str
 22  peak-rpm           205 non-null    str
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    str
dtypes: float64(5), int64(5), str(16)
memory usage: 41.8 KB

#### Cleaning

In [4]:
data = data.replace(-1, np.nan)
data = data.replace('?', np.nan)

In [5]:
data

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3.0,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3.0,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1.0,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2.0,164,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2.0,164,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,NaN,95,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5,2952,ohc,four,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,NaN,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,55.5,3049,ohc,four,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,NaN,95,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5,3012,ohcv,six,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,NaN,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5,3217,ohc,six,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,NaN,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5,3062,ohc,four,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          183 non-null    float64
 1   normalized-losses  164 non-null    str
 2   make               205 non-null    str
 3   fuel-type          205 non-null    str
 4   aspiration         205 non-null    str
 5   num-of-doors       203 non-null    str
 6   body-style         205 non-null    str
 7   drive-wheels       205 non-null    str
 8   engine-location    205 non-null    str
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    str
 15  num-of-cylinders   205 non-null    str
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    str
 18  bore               201 non-null    str
 19  stroke             201 non-null    str
 20  compression-ratio  205 non-null    float64
 21  horsepower         203 non-null    str
 22  peak-rpm           203 non-null    str
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              201 non-null    str
dtypes: float64(6), int64(4), str(16)
memory usage: 41.8 KB

In [7]:
for column in ['normalized-losses', 'bore', 'stroke', 'horsepower', 'peak-rpm', 'price']:
    data[column] = data[column].astype(float)

In [8]:
data.isna().sum()

symboling            22
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

In [9]:
for column in data.columns:
    if data.dtypes[column] != 'str' and data.isna().sum()[column] > 0:  # For all numerical columns with missing values
        data[column] = data[column].fillna(data[column].mean()) #  Fill missing values with the column's mean

In [10]:
data.isna().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         2
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

#### Encoding ordinal features

In [11]:
{column: list(data[column].unique()) for column in data.columns if data.dtypes[column] == 'str'}

{'make': ['alfa-romero',
  'audi',
  'bmw',
  'chevrolet',
  'dodge',
  'honda',
  'isuzu',
  'jaguar',
  'mazda',
  'mercedes-benz',
  'mercury',
  'mitsubishi',
  'nissan',
  'peugot',
  'plymouth',
  'porsche',
  'renault',
  'saab',
  'subaru',
  'toyota',
  'volkswagen',
  'volvo'],
 'fuel-type': ['gas', 'diesel'],
 'aspiration': ['std', 'turbo'],
 'num-of-doors': ['two', 'four', nan],
 'body-style': ['convertible', 'hatchback', 'sedan', 'wagon', 'hardtop'],
 'drive-wheels': ['rwd', 'fwd', '4wd'],
 'engine-location': ['front', 'rear'],
 'engine-type': ['dohc', 'ohcv', 'ohc', 'l', 'rotor', 'ohcf', 'dohcv'],
 'num-of-cylinders': ['four',
  'six',
  'five',
  'three',
  'twelve',
  'two',
  'eight'],
 'fuel-system': ['mpfi', '2bbl', 'mfi', '1bbl', 'spfi', '4bbl', 'idi', 'spdi']}

In [12]:
num_cyl_ordering = {
    'two': 2,
    'three': 3,
    'four': 4,
    'five': 5,
    'six': 6,
    'eight': 8,
    'twelve': 12
}

data['num-of-cylinders'] = data['num-of-cylinders'].replace(num_cyl_ordering)

In [13]:
data

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3.000000,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,4,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3.000000,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,4,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1.000000,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,6,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2.000000,164.0,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,4,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2.000000,164.0,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,5,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,1.054645,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5,2952,ohc,4,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,1.054645,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,55.5,3049,ohc,4,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,1.054645,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5,3012,ohcv,6,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,1.054645,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5,3217,ohc,6,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,1.054645,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5,3062,ohc,4,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

In [14]:
data['num-of-doors'].mode()

0    four
Name: num-of-doors, dtype: str

In [15]:
# Filling remaining missing values
data['num-of-doors'] = data['num-of-doors'].apply(lambda x: 0 if x == 'two' else 1)

#### Filling remaining missing values

In [16]:
print("Total missing values:", data.isna().sum().sum())

Total missing values: 0

#### Encoding

In [17]:
def binary_encode(df, columns, positive_values):
    df = df.copy()
    for column, positive_value in zip(columns, positive_values):
        df[column] = df[column].apply(lambda x: 1 if x == positive_value else 0)
    return df

In [18]:
{column: list(data[column].unique()) for column in data.columns if data.dtypes[column] == 'str'}

{'make': ['alfa-romero',
  'audi',
  'bmw',
  'chevrolet',
  'dodge',
  'honda',
  'isuzu',
  'jaguar',
  'mazda',
  'mercedes-benz',
  'mercury',
  'mitsubishi',
  'nissan',
  'peugot',
  'plymouth',
  'porsche',
  'renault',
  'saab',
  'subaru',
  'toyota',
  'volkswagen',
  'volvo'],
 'fuel-type': ['gas', 'diesel'],
 'aspiration': ['std', 'turbo'],
 'body-style': ['convertible', 'hatchback', 'sedan', 'wagon', 'hardtop'],
 'drive-wheels': ['rwd', 'fwd', '4wd'],
 'engine-location': ['front', 'rear'],
 'engine-type': ['dohc', 'ohcv', 'ohc', 'l', 'rotor', 'ohcf', 'dohcv'],
 'fuel-system': ['mpfi', '2bbl', 'mfi', '1bbl', 'spfi', '4bbl', 'idi', 'spdi']}

In [19]:
binary_features = ['fuel-type', 'aspiration', 'engine-location']

binary_positive_values = ['diesel', 'turbo', 'front']

data = binary_encode(
    data,
    binary_features,
    binary_positive_values
)

In [20]:
def onehot_encode(df, columns, prefixes):
    df = df.copy()
    for column, prefix in zip(columns, prefixes):
        dummies = pd.get_dummies(df[column], dtype=int, prefix=prefix)
        df = pd.concat([df, dummies], axis=1)
        df = df.drop(column, axis=1)
    return df

In [21]:
nominal_features = ['make', 'drive-wheels', 'engine-type', 'fuel-system', 'body-style']

nominal_prefixes = ['m', 'dw', 'et', 'fs', 'bs']

data = onehot_encode(
    data,
    nominal_features, 
    nominal_prefixes
)

In [22]:
data

,symboling,normalized-losses,fuel-type,aspiration,num-of-doors,engine-location,wheel-base,length,width,height,curb-weight,num-of-cylinders,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,m_alfa-romero,m_audi,m_bmw,m_chevrolet,m_dodge,m_honda,m_isuzu,m_jaguar,m_mazda,m_mercedes-benz,m_mercury,m_mitsubishi,m_nissan,m_peugot,m_plymouth,m_porsche,m_renault,m_saab,m_subaru,m_toyota,m_volkswagen,m_volvo,dw_4wd,dw_fwd,dw_rwd,et_dohc,et_dohcv,et_l,et_ohc,et_ohcf,et_ohcv,et_rotor,fs_1bbl,fs_2bbl,fs_4bbl,fs_idi,fs_mfi,fs_mpfi,fs_spdi,fs_spfi,bs_convertible,bs_hardtop,bs_hatchback,bs_sedan,bs_wagon
0,3.000000,122.0,0,0,0,1,88.6,168.8,64.1,48.8,2548,4,130,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0
1,3.000000,122.0,0,0,0,1,88.6,168.8,64.1,48.8,2548,4,130,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0
2,1.000000,122.0,0,0,0,1,94.5,171.2,65.5,52.4,2823,6,152,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0
3,2.000000,164.0,0,0,1,1,99.8,176.6,66.2,54.3,2337,4,109,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0
4,2.000000,164.0,0,0,1,1,99.4,176.6,66.4,54.3,2824,5,136,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,1.054645,95.0,0,0,1,1,109.1,188.8,68.9,55.5,2952,4,141,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0
201,1.054645,95.0,0,1,1,1,109.1,188.8,68.8,55.5,3049,4,141,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0
202,1.054645,95.0,0,0,1,1,109.1,188.8,68.9,55.5,3012,6,173,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0
203,1.054645,95.0,1,1,1,1,109.1,188.8,68.9,55.5,3217,6,145,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0
204,1.054645,95.0,0,1,1,1,109.1,188.8,68.9,55.5,3062,4,141,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0

In [23]:
print("Total non-numeric columns:", (data.dtypes=='str').sum())

Total non-numeric columns: 0

#### Splitting/Scaling

In [24]:
y = data['price'].copy()
X = data.drop('price', axis=1).copy()

In [25]:
scaler = StandardScaler()

X = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, shuffle=True, random_state=20)

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=20)

In [27]:
X_train

,symboling,normalized-losses,fuel-type,aspiration,num-of-doors,engine-location,wheel-base,length,width,height,curb-weight,num-of-cylinders,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,m_alfa-romero,m_audi,m_bmw,m_chevrolet,m_dodge,m_honda,m_isuzu,m_jaguar,m_mazda,m_mercedes-benz,m_mercury,m_mitsubishi,m_nissan,m_peugot,m_plymouth,m_porsche,m_renault,m_saab,m_subaru,m_toyota,m_volkswagen,m_volvo,dw_4wd,dw_fwd,dw_rwd,et_dohc,et_dohcv,et_l,et_ohc,et_ohcf,et_ohcv,et_rotor,fs_1bbl,fs_2bbl,fs_4bbl,fs_idi,fs_mfi,fs_mpfi,fs_spdi,fs_spfi,bs_convertible,bs_hardtop,bs_hatchback,bs_sedan,bs_wagon
127,1.822954e+00,0.000000,-0.328798,-0.469295,-1.141653,-8.205689,-1.540948,-0.418396,-0.424215,-0.871725,0.385889,1.502032,1.615095,1.518415,-1.136149,-0.162161,2.606210,1.628010,-1.259470,-0.837195,-0.121867,-0.188025,-0.201517,-0.121867,-0.214286,-0.260208,-0.141069,-0.121867,-0.300708,-0.201517,-0.070014,-0.260208,-0.310253,-0.23812,-0.188025,6.324555,-0.099258,-0.17364,-0.249351,-0.430083,-0.249351,-0.23812,-0.214286,-1.188177,1.302831,-0.249351,-0.070014,-0.249351,-1.611363,3.559026,-0.260208,-0.141069,-0.238120,-0.689072,-0.121867,-0.328798,-0.070014,1.086670,-0.214286,-0.070014,-0.173640,4.962358,-0.720082,-0.938474,-0.372678
177,2.080736e-16,-1.803590,-0.328798,-0.469295,0.875923,0.121867,0.606521,0.126002,0.276731,0.071843,-0.187840,-0.352887,-0.118132,-0.073103,0.909683,-0.364062,-0.310891,-1.944812,0.272823,0.181783,-0.121867,-0.188025,-0.201517,-0.121867,-0.214286,-0.260208,-0.141069,-0.121867,-0.300708,-0.201517,-0.070014,-0.260208,-0.310253,-0.23812,-0.188025,-0.158114,-0.099258,-0.17364,-0.249351,2.325134,-0.249351,-0.23812,-0.214286,0.841625,-0.767559,-0.249351,-0.070014,-0.249351,0.620593,-0.280976,-0.260208,-0.141069,-0.238120,-0.689072,-0.121867,-0.328798,-0.070014,1.086670,-0.214286,-0.070014,-0.173640,-0.201517,1.388730,-0.938474,-0.372678
0,1.822954e+00,0.000000,-0.328798,-0.469295,-1.141653,0.121867,-1.690772,-0.426521,-0.844782,-2.020417,-0.014566,-0.352887,0.074449,0.519089,-1.839404,-0.288349,0.171065,-0.263484,-0.646553,-0.546059,8.205689,-0.188025,-0.201517,-0.121867,-0.214286,-0.260208,-0.141069,-0.121867,-0.300708,-0.201517,-0.070014,-0.260208,-0.310253,-0.23812,-0.188025,-0.158114,-0.099258,-0.17364,-0.249351,-0.430083,-0.249351,-0.23812,-0.214286,-1.188177,1.302831,4.010403,-0.070014,-0.249351,-1.611363,-0.280976,-0.260208,-0.141069,-0.238120,-0.689072,-0.121867,-0.328798,-0.070014,1.086670,-0.214286,-0.070014,5.759051,-0.201517,-0.720082,-0.938474,-0.372678
40,-9.882866e-01,-1.170751,-0.328798,-0.469295,0.875923,0.121867,-0.375655,0.109752,-1.592458,0.153893,-0.353413,-0.352887,-0.407003,-0.665296,1.037547,-0.288349,-0.463087,1.417844,0.272823,0.327351,-0.121867,-0.188025,-0.201517,-0.121867,-0.214286,3.843076,-0.141069,-0.121867,-0.300708,-0.201517,-0.070014,-0.260208,-0.310253,-0.23812,-0.188025,-0.158114,-0.099258,-0.17364,-0.249351,-0.430083,-0.249351,-0.23812,-0.214286,0.841625,-0.767559,-0.249351,-0.070014,-0.249351,0.620593,-0.280976,-0.260208,-0.141069,4.199567,-0.689072,-0.121867,-0.328798,-0.070014,-0.920243,-0.214286,-0.070014,-0.173640,-0.201517,-0.720082,1.065559,-0.372678
6,-5.120656e-02,1.139109,-0.328798,-0.469295,0.875923,0.121867,1.172521,1.515437,2.566488,0.810288,0.555313,0.574572,0.218885,-0.517248,0.462157,-0.414537,0.145699,0.787346,-0.953012,-0.837195,-0.121867,5.318432,-0.201517,-0.121867,-0.214286,-0.260208,-0.141069,-0.121867,-0.300708,-0.201517,-0.070014,-0.260208,-0.310253,-0.23812,-0.188025,-0.158114,-0.099258,-0.17364,-0.249351,-0.430083,-0.249351,-0.23812,-0.214286,0.841625,-0.767559,-0.249351,-0.070014,-0.249351,0.620593,-0.280976,-0.260208,-0.141069,-0.238120,-0.689072,-0.121867,-0.328798,-0.070014,1.086670,-0.214286,-0.070014,-0.173640,-0.201517,-0.720082,1.065559,-0.372678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,-9.882866e-01,-0.506271,-0.328798,-0.469295,0.875923,0.121867,-0.259126,-0.052755,-0.330755,0.400041,-0.488182,-0.352887,-0.166277,0.000921,0.685920,-0.414537,-0.184060,0.156848,0.272823,0.472920,-0.121867,-0.188025,-0.201517,-0.121867,-0.214286,-0.260208,-0.141069,-0.121867,-0.300708,-0.201517,-0.070014,-0.260208,3.223180,-0.23812,-0.188025,-0.158114,-0.099258,-0.17364,-0.249351,-0.430083,-0.249351,-0.23812,-0.214286,0.841625,-0.767559,-0.249351,-0.070014,-0.249351,0.620593,-0.280976,-0.260208,-0.141069,-0.238120,1.451227,-0.121867,-0.328798,-0.070014,-0.920243,-0.214286,-0.070014,-0.173640,-0.201517,-0.720082,1.065559,-0.372678
158,-9.882866e-01,-0.980900,3.041381,-0.469295,0.875923,0.121867,-0.508831,-0.629655,-0.704593,-0.297379,-0.540164,-0.352887,-0.407003,-0.221152,0.302326,3.118728,-1.224070,-1.314314,1.345428,0.764056,-0.121867,-0.188025,-0.201517,-0.121867,-0.214286,-0.260208,-0.141069,-0.121867,-0.300708,-0.201517,-0.070014,-0.260208,-0.310253,-0.23812,-0.188025,-0.158114,-0.099258,-0.17364,-0.249351,2.325134,-0.249351,-0.23812,-0.214286,0.841625,-0.767559,-0.249351,-0.070014,-0.249351,0.620593,-0.280976,-0.260208,-0.141069,-0.238120,-0.689072,-0.121867,3.041381,-0.070014,-0.920243,-0.214286,-0.070014,-0.173640,-0.201517,-0.720082,1.065559,-0.372678
75,-5.120656e-02,0.000000,-0.328798,2.130854,-1.141653,0.121867,0.656462,0.353512,0.977677,0.441066,0.682380,-0.352887,0.315175,1.666463,-0.432894,-0.540725,1.794495,-0.263484,-0.953012,-0.982764,-0.121867,-0.188025,-0.201517,-0.121867,-0.214286,-0.260208,-0.141069,-0.121867,-0.300708,-0.201517,14.282857,-0.260208,-0.310253,-0.23812,-0.188025,-0.158114,-0.099258,-0.17364,-0.249351,-0.430083,-0.249351,-0.23812,-0.214286,-1.188177,1.302831,-0.249351,-0.070014,-0.249351,0.620593,-0.280976,-0.260208,-0.141069,-0.238120,-0.689072,-0.121867,-0.328798,-0.070014,1.086670,-0.214286,-0.070014,-0.173640,-0.201517,1.388730,-0.938474,-0.372678
98,8.858735e-01,1.455528,-0.328798,-0.469295,-1.141653,0.121867,-0.608714,-0.946544,-0.984972,-0.174305,-1.054210,-0.352887,-0.719947,-0.665296,0.110530,-0.187398,-0.894311,0.156848,0.885740,0.909625,-0.121867,-0.188025,-0.201517,-0.121867,-0.214286,-0.260208,-0.141069,-0.121867,-0.300708,-0.201517,-0.070014,-0.260208,3.223180,-0.23812,-0.188025,-0.158114,-0.099258,-0.17364,-0.249351,-0.430083,-0.249351,-0.23812,-0.214286,0.841625,-0.767559,-0.249351,-0.070014,-0.249351,0.620593,-0.280976,-0.260208,-0.141069,-0.238120,1.451227,-0.121867,-0.328798,-0.070014,-0.920243,-0.214286,-0.070014,-0.173640,4.962358,-0.720082,-0.938474,-0.372678
146,-9.882866e-01,-1.044183,-0.328798,-0.469295,0.875923,0.121867,-0.292420,-0.044630,-0.237296,-0.297379,-0.511285,-0.352887,-0.455148,1.074270,-1.967268,-0.288349,-0.564552,-0.683816,0.426052,0.181783,-0.121867,-0.188025,-0.201517,-0.121867,-0.214286,-0.260208,-0.141069,-0.121867,-0.300708,-0.201517,-0.070014,-0.260208,-0.310253,-0.23812,-0.188025,-0.158114,-0.099258,-0.17364,4.010403,-0.430083,-0.249351,-0.23812,-0.214286,0.841625,-0.767559,-0.249351,-0.070014,-0.249351,-1.611363,3.559026,-0.260208,-0.141069,-0.238120,1.451227,-0.121867,-0.328798,-0.070014,-0.920243,-0.214286,-0.070014,-0.173640,-0.201517,-0.720082,-0.938474,2.683282

In [28]:
dtrain = xgb.DMatrix(X_train, label=y_train)
dval = xgb.DMatrix(X_val, label=y_val)
dtest = xgb.DMatrix(X_test, label=y_test)

### Training

In [ ]:
params = {'learning_rate': 0.001, 'max_depth': 6}

model = xgb.train(params, dtrain, evals=[(dval, 'eval')], num_boost_round=10000, early_stopping_rounds=10)

[0]	eval-rmse:10637.36224
[1]	eval-rmse:10629.64647
[2]	eval-rmse:10621.93815
[3]	eval-rmse:10614.23738
[4]	eval-rmse:10606.54423
[5]	eval-rmse:10598.85931
[6]	eval-rmse:10591.18107
[7]	eval-rmse:10583.51133
[8]	eval-rmse:10575.84855
[9]	eval-rmse:10568.19359
[10]	eval-rmse:10560.54579
[11]	eval-rmse:10552.90619
[12]	eval-rmse:10545.27402
[13]	eval-rmse:10537.64937
[14]	eval-rmse:10530.03236
[15]	eval-rmse:10522.42289
[16]	eval-rmse:10514.82087
[17]	eval-rmse:10507.22653
[18]	eval-rmse:10499.63956
[19]	eval-rmse:10492.06025
[20]	eval-rmse:10484.48859
[21]	eval-rmse:10476.92444
[22]	eval-rmse:10469.36760
[23]	eval-rmse:10461.64207
[24]	eval-rmse:10454.10019
[25]	eval-rmse:10446.56546
[26]	eval-rmse:10438.86261
[27]	eval-rmse:10431.34285
[28]	eval-rmse:10423.83111
[29]	eval-rmse:10416.15041
[30]	eval-rmse:10408.65385
[31]	eval-rmse:10401.16384
[32]	eval-rmse:10393.50618
[33]	eval-rmse:10386.03113
[34]	eval-rmse:10378.56363
[35]	eval-rmse:10370.92855
[36]	eval-rmse:10363.47539
[37]	eval-rmse:10356.03022
[38]	eval-rmse:10348.41724
[39]	eval-rmse:10340.98586
[40]	eval-rmse:10333.56264
[41]	eval-rmse:10325.97241
[42]	eval-rmse:10318.56337
[43]	eval-rmse:10311.16279
[44]	eval-rmse:10303.59454
[45]	eval-rmse:10296.17932
[46]	eval-rmse:10288.77096
[47]	eval-rmse:10281.22558
[48]	eval-rmse:10273.83210
[49]	eval-rmse:10266.44627
[50]	eval-rmse:10258.92222
[51]	eval-rmse:10251.55112
[52]	eval-rmse:10244.18699
[53]	eval-rmse:10236.68570
[54]	eval-rmse:10229.33573
[55]	eval-rmse:10221.99387
[56]	eval-rmse:10214.48631
[57]	eval-rmse:10207.18630
[58]	eval-rmse:10199.86564
[59]	eval-rmse:10192.37989
[60]	eval-rmse:10185.10223
[61]	eval-rmse:10177.80275
[62]	eval-rmse:10170.33899
[63]	eval-rmse:10163.08304
[64]	eval-rmse:10155.80578
[65]	eval-rmse:10148.36405
[66]	eval-rmse:10141.10114
[67]	eval-rmse:10133.87364
[68]	eval-rmse:10126.45329
[69]	eval-rmse:10119.21185
[70]	eval-rmse:10112.00609
[71]	eval-rmse:10104.60761
[72]	eval-rmse:10097.38795
[73]	eval-rmse:10090.17579
[74]	eval-rmse:10082.82748
[75]	eval-rmse:10075.62949
[76]	eval-rmse:10068.43838
[77]	eval-rmse:10061.11110
[78]	eval-rmse:10053.93407
[79]	eval-rmse:10046.76390
[80]	eval-rmse:10039.45867
[81]	eval-rmse:10032.30314
[82]	eval-rmse:10025.20837
[83]	eval-rmse:10018.12108
[84]	eval-rmse:10010.84467
[85]	eval-rmse:10003.77108
[86]	eval-rmse:9996.70492
[87]	eval-rmse:9989.67331
[88]	eval-rmse:9982.62165
[89]	eval-rmse:9975.35318
[90]	eval-rmse:9968.34340
[91]	eval-rmse:9961.31295
[92]	eval-rmse:9954.29016
[93]	eval-rmse:9947.25532
[94]	eval-rmse:9940.04992
[95]	eval-rmse:9933.04758
[96]	eval-rmse:9926.03451
[97]	eval-rmse:9919.05521
[98]	eval-rmse:9912.05600
[99]	eval-rmse:9905.08254
[100]	eval-rmse:9897.89283
[101]	eval-rmse:9890.94163
[102]	eval-rmse:9883.97117
[103]	eval-rmse:9877.00697
[104]	eval-rmse:9870.09625
[105]	eval-rmse:9863.14648
[106]	eval-rmse:9855.99906
[107]	eval-rmse:9849.09019
[108]	eval-rmse:9842.16167
[109]	eval-rmse:9835.25852
[110]	eval-rmse:9828.34450
[111]	eval-rmse:9821.46430
[112]	eval-rmse:9814.58236
[113]	eval-rmse:9807.48357
[114]	eval-rmse:9800.62422
[115]	eval-rmse:9793.74482
[116]	eval-rmse:9786.87250
[117]	eval-rmse:9780.05235
[118]	eval-rmse:9773.19429
[119]	eval-rmse:9766.29041
[120]	eval-rmse:9759.46449
[121]	eval-rmse:9752.65382
[122]	eval-rmse:9745.61748
[123]	eval-rmse:9738.79412
[124]	eval-rmse:9732.00402
[125]	eval-rmse:9725.21237
[126]	eval-rmse:9718.41016
[127]	eval-rmse:9711.64065
[128]	eval-rmse:9704.85214
[129]	eval-rmse:9697.86350
[130]	eval-rmse:9691.10712
[131]	eval-rmse:9684.36565
[132]	eval-rmse:9677.60396
[133]	eval-rmse:9670.84916
[134]	eval-rmse:9664.14661
[135]	eval-rmse:9657.20026
[136]	eval-rmse:9650.46659
[137]	eval-rmse:9643.76612
[138]	eval-rmse:9637.04606
[139]	eval-rmse:9630.35084
[140]	eval-rmse:9623.64454
[141]	eval-rmse:9616.74094
[142]	eval-rmse:9610.05004
[143]	eval-rmse:9603.39083
[144]	eval-rmse:9596.73253
[145]	eval-rmse:9590.08667
[146]	eval-rmse:9583.42315
[147]	eval-rmse:9576.73731
[148]	eval-rmse:9570.10604
[149]	eval-rmse:9563.46065
[150]	eval-rmse:9556.61801
[151]	eval-rmse:9549.98844
[152]	eval-rmse:9543.40784
[153]	eval-rmse:9536.79172
[154]	eval-rmse:9530.20660
[155]	eval-rmse:9523.62239
[156]	eval-rmse:9516.82030
[157]	eval-rmse:9510.25562
[158]	eval-rmse:9503.67295
[159]	eval-rmse:9497.09691
[160]	eval-rmse:9490.54635
[161]	eval-rmse:9483.98471
[162]	eval-rmse:9477.22288
[163]	eval-rmse:9470.67415
[164]	eval-rmse:9464.15606
[165]	eval-rmse:9457.63878
[166]	eval-rmse:9451.11032
[167]	eval-rmse:9444.58866
[168]	eval-rmse:9438.07338
[169]	eval-rmse:9431.35827
[170]	eval-rmse:9424.87435
[171]	eval-rmse:9418.40288
[172]	eval-rmse:9411.91442
[173]	eval-rmse:9405.43276
[174]	eval-rmse:9398.97596
[175]	eval-rmse:9392.30002
[176]	eval-rmse:9385.83867
[177]	eval-rmse:9379.38301
[178]	eval-rmse:9372.93404
[179]	eval-rmse:9366.53370
[180]	eval-rmse:9360.04232
[181]	eval-rmse:9353.61372
[182]	eval-rmse:9347.20947
[183]	eval-rmse:9340.58690
[184]	eval-rmse:9334.17777
[185]	eval-rmse:9327.77529
[186]	eval-rmse:9321.40228
[187]	eval-rmse:9315.03054
[188]	eval-rmse:9308.64790
[189]	eval-rmse:9302.06507
[190]	eval-rmse:9295.69517
[191]	eval-rmse:9289.33201
[192]	eval-rmse:9282.99321
[193]	eval-rmse:9276.66609
[194]	eval-rmse:9270.32260
[195]	eval-rmse:9263.77883
[196]	eval-rmse:9257.44818
[197]	eval-rmse:9251.14200
[198]	eval-rmse:9244.82421
[199]	eval-rmse:9238.51315
[200]	eval-rmse:9232.24931
[201]	eval-rmse:9225.74413
[202]	eval-rmse:9219.45269
[203]	eval-rmse:9213.16725
[204]	eval-rmse:9206.87940
[205]	eval-rmse:9200.62499
[206]	eval-rmse:9194.35917
[207]	eval-rmse:9187.89303
[208]	eval-rmse:9181.63072
[209]	eval-rmse:9175.38433
[210]	eval-rmse:9169.16165
[211]	eval-rmse:9162.92827
[212]	eval-rmse:9156.69220
[213]	eval-rmse:9150.26441
[214]	eval-rmse:9144.05019
[215]	eval-rmse:9137.85053
[216]	eval-rmse:9131.64937
[217]	eval-rmse:9125.45444
[218]	eval-rmse:9119.05886
[219]	eval-rmse:9112.86736
[220]	eval-rmse:9106.69396
[221]	eval-rmse:9100.52442
[222]	eval-rmse:9094.36106
[223]	eval-rmse:9088.19774
[224]	eval-rmse:9081.83975
[225]	eval-rmse:9075.69567
[226]	eval-rmse:9069.54285
[227]	eval-rmse:9063.40265
[228]	eval-rmse:9057.29489
[229]	eval-rmse:9051.10248
[230]	eval-rmse:9044.99013
[231]	eval-rmse:9038.87724
[232]	eval-rmse:9032.57011
[233]	eval-rmse:9026.47663
[234]	eval-rmse:9020.36521
[235]	eval-rmse:9014.28433
[236]	eval-rmse:9008.22684
[237]	eval-rmse:9002.14396
[238]	eval-rmse:8995.86561
[239]	eval-rmse:8989.80956
[240]	eval-rmse:8983.74542
[241]	eval-rmse:8977.71942
[242]	eval-rmse:8971.67346
[243]	eval-rmse:8965.62802
[244]	eval-rmse:8959.39608
[245]	eval-rmse:8953.36281
[246]	eval-rmse:8947.35958
[247]	eval-rmse:8941.35374
[248]	eval-rmse:8935.33923
[249]	eval-rmse:8929.12931
[250]	eval-rmse:8923.14229
[251]	eval-rmse:8917.16375
[252]	eval-rmse:8911.18882
[253]	eval-rmse:8905.21126
[254]	eval-rmse:8899.23435
[255]	eval-rmse:8893.00507
[256]	eval-rmse:8887.07168
[257]	eval-rmse:8881.10436
[258]	eval-rmse:8875.16683
[259]	eval-rmse:8869.22053
[260]	eval-rmse:8863.02235
[261]	eval-rmse:8857.11130
[262]	eval-rmse:8851.18313
[263]	eval-rmse:8845.34352
[264]	eval-rmse:8839.44269
[265]	eval-rmse:8833.63224
[266]	eval-rmse:8827.47086
[267]	eval-rmse:8821.65534
[268]	eval-rmse:8815.77869
[269]	eval-rmse:8809.97582
[270]	eval-rmse:8804.12871
[271]	eval-rmse:8798.06540
[272]	eval-rmse:8792.21330
[273]	eval-rmse:8786.39126
[274]	eval-rmse:8780.55144
[275]	eval-rmse:8774.75842
[276]	eval-rmse:8768.93106
[277]	eval-rmse:8762.86154
[278]	eval-rmse:8757.04610
[279]	eval-rmse:8751.22194
[280]	eval-rmse:8745.45958
[281]	eval-rmse:8739.68630
[282]	eval-rmse:8733.84543
[283]	eval-rmse:8728.08436
[284]	eval-rmse:8722.30496
[285]	eval-rmse:8716.28370
[286]	eval-rmse:8710.51625
[287]	eval-rmse:8704.77909
[288]	eval-rmse:8699.04026
[289]	eval-rmse:8693.29091
[290]	eval-rmse:8687.29959
[291]	eval-rmse:8681.54741
[292]	eval-rmse:8675.84030
[293]	eval-rmse:8670.15579
[294]	eval-rmse:8664.43611
[295]	eval-rmse:8658.74718
[296]	eval-rmse:8652.76756
[297]	eval-rmse:8647.09046
[298]	eval-rmse:8641.41128
[299]	eval-rmse:8635.74612
[300]	eval-rmse:8630.06250
[301]	eval-rmse:8624.11299
[302]	eval-rmse:8618.46557
[303]	eval-rmse:8612.81619
[304]	eval-rmse:8607.18092
[305]	eval-rmse:8601.52703
[306]	eval-rmse:8595.92021
[307]	eval-rmse:8589.99160
[308]	eval-rmse:8584.37953
[309]	eval-rmse:8578.77357
[310]	eval-rmse:8573.14882
[311]	eval-rmse:8567.54654
[312]	eval-rmse:8561.68702
[313]	eval-rmse:8556.08023
[314]	eval-rmse:8550.50405
[315]	eval-rmse:8544.90844
[316]	eval-rmse:8539.35985
[317]	eval-rmse:8533.50496
[318]	eval-rmse:8527.95203
[319]	eval-rmse:8522.38025
[320]	eval-rmse:8516.80006
[321]	eval-rmse:8511.28057
[322]	eval-rmse:8505.47966
[323]	eval-rmse:8499.93095
[324]	eval-rmse:8494.41314
[325]	eval-rmse:8488.87628
[326]	eval-rmse:8483.38608
[327]	eval-rmse:8477.58975
[328]	eval-rmse:8472.09505
[329]	eval-rmse:8466.58150
[330]	eval-rmse:8461.07377
[331]	eval-rmse:8455.61240
[332]	eval-rmse:8450.11620
[333]	eval-rmse:8444.37981
[334]	eval-rmse:8438.89518
[335]	eval-rmse:8433.44085
[336]	eval-rmse:8427.96948
[337]	eval-rmse:8422.52686
[338]	eval-rmse:8416.81928
[339]	eval-rmse:8411.36315
[340]	eval-rmse:8405.91278
[341]	eval-rmse:8400.50901
[342]	eval-rmse:8395.06987
[343]	eval-rmse:8389.29633
[344]	eval-rmse:8383.86886
[345]	eval-rmse:8378.47177
[346]	eval-rmse:8373.07177
[347]	eval-rmse:8367.85688
[348]	eval-rmse:8362.16741
[349]	eval-rmse:8356.96281
[350]	eval-rmse:8351.67588
[351]	eval-rmse:8346.47297
[352]	eval-rmse:8341.11422
[353]	eval-rmse:8335.63600
[354]	eval-rmse:8330.45827
[355]	eval-rmse:8325.26071
[356]	eval-rmse:8319.91452
[357]	eval-rmse:8314.75247
[358]	eval-rmse:8309.30055
[359]	eval-rmse:8303.97964
[360]	eval-rmse:8298.80778
[361]	eval-rmse:8293.68252
[362]	eval-rmse:8288.50737
[363]	eval-rmse:8282.88971
[364]	eval-rmse:8277.76396
[365]	eval-rmse:8272.61820
[366]	eval-rmse:8267.46985
[367]	eval-rmse:8262.19205
[368]	eval-rmse:8257.06193
[369]	eval-rmse:8251.66765
[370]	eval-rmse:8246.57330
[371]	eval-rmse:8241.28347
[372]	eval-rmse:8236.17403
[373]	eval-rmse:8231.09520
[374]	eval-rmse:8225.72703
[375]	eval-rmse:8220.41208
[376]	eval-rmse:8215.32320
[377]	eval-rmse:8210.26513
[378]	eval-rmse:8205.18679
[379]	eval-rmse:8199.70333
[380]	eval-rmse:8194.67622
[381]	eval-rmse:8189.59952
[382]	eval-rmse:8184.47187
[383]	eval-rmse:8179.27868
[384]	eval-rmse:8173.96234
[385]	eval-rmse:8168.96079
[386]	eval-rmse:8163.94878
[387]	eval-rmse:8158.75113
[388]	eval-rmse:8153.72379
[389]	eval-rmse:8148.45872
[390]	eval-rmse:8143.38792
[391]	eval-rmse:8138.21128
[392]	eval-rmse:8133.22968
[393]	eval-rmse:8128.22774
[394]	eval-rmse:8122.98841
[395]	eval-rmse:8117.83376
[396]	eval-rmse:8112.87283
[397]	eval-rmse:8107.82197
[398]	eval-rmse:8102.81406
[399]	eval-rmse:8097.67873
[400]	eval-rmse:8092.73794
[401]	eval-rmse:8087.50825
[402]	eval-rmse:8082.57726
[403]	eval-rmse:8077.47768
[404]	eval-rmse:8072.55705
[405]	eval-rmse:8067.54675
[406]	eval-rmse:8062.34267
[407]	eval-rmse:8057.27440
[408]	eval-rmse:8052.36318
[409]	eval-rmse:8047.42832
[410]	eval-rmse:8042.53802
[411]	eval-rmse:8037.22237
[412]	eval-rmse:8032.24679
[413]	eval-rmse:8027.38684
[414]	eval-rmse:8022.49064
[415]	eval-rmse:8017.46317
[416]	eval-rmse:8012.30897
[417]	eval-rmse:8007.45355
[418]	eval-rmse:8002.52322
[419]	eval-rmse:7997.49043
[420]	eval-rmse:7992.38252
[421]	eval-rmse:7987.53870
[422]	eval-rmse:7982.52129
[423]	eval-rmse:7977.67108
[424]	eval-rmse:7972.85038
[425]	eval-rmse:7967.76722
[426]	eval-rmse:7962.79617
[427]	eval-rmse:7957.96417
[428]	eval-rmse:7953.17827
[429]	eval-rmse:7948.28757
[430]	eval-rmse:7943.06127
[431]	eval-rmse:7938.24847
[432]	eval-rmse:7933.48233
[433]	eval-rmse:7928.67946
[434]	eval-rmse:7923.74838
[435]	eval-rmse:7918.67540
[436]	eval-rmse:7913.91347
[437]	eval-rmse:7909.17190
[438]	eval-rmse:7904.26117
[439]	eval-rmse:7899.50520
[440]	eval-rmse:7894.47032
[441]	eval-rmse:7889.73309
[442]	eval-rmse:7884.83097
[443]	eval-rmse:7880.00883
[444]	eval-rmse:7874.99346
[445]	eval-rmse:7870.27541
[446]	eval-rmse:7865.37793
[447]	eval-rmse:7860.68481
[448]	eval-rmse:7855.98156
[449]	eval-rmse:7851.00809
[450]	eval-rmse:7846.11958
[451]	eval-rmse:7841.43104
[452]	eval-rmse:7836.66699
[453]	eval-rmse:7831.98817
[454]	eval-rmse:7826.86419
[455]	eval-rmse:7822.17045
[456]	eval-rmse:7817.50576
[457]	eval-rmse:7812.86111
[458]	eval-rmse:7808.02424
[459]	eval-rmse:7803.10617
[460]	eval-rmse:7798.36591
[461]	eval-rmse:7793.64376
[462]	eval-rmse:7788.81391
[463]	eval-rmse:7783.91524
[464]	eval-rmse:7779.19421
[465]	eval-rmse:7774.49125
[466]	eval-rmse:7769.66602
[467]	eval-rmse:7765.01567
[468]	eval-rmse:7760.04645
[469]	eval-rmse:7755.39115
[470]	eval-rmse:7750.55701
[471]	eval-rmse:7745.86941
[472]	eval-rmse:7741.29562
[473]	eval-rmse:7736.39224
[474]	eval-rmse:7731.56424
[475]	eval-rmse:7726.90903
[476]	eval-rmse:7722.28710
[477]	eval-rmse:7717.64267
[478]	eval-rmse:7712.66145
[479]	eval-rmse:7708.02515
[480]	eval-rmse:7703.42182
[481]	eval-rmse:7698.79641
[482]	eval-rmse:7693.78227
[483]	eval-rmse:7689.19330
[484]	eval-rmse:7684.58071
[485]	eval-rmse:7679.80619
[486]	eval-rmse:7675.29846
[487]	eval-rmse:7670.46150
[488]	eval-rmse:7665.86755
[489]	eval-rmse:7661.11245
[490]	eval-rmse:7656.55624
[491]	eval-rmse:7651.97755
[492]	eval-rmse:7647.21645
[493]	eval-rmse:7642.52172
[494]	eval-rmse:7637.95567
[495]	eval-rmse:7633.38091
[496]	eval-rmse:7628.58620
[497]	eval-rmse:7623.86927
[498]	eval-rmse:7619.41674
[499]	eval-rmse:7614.87385
[500]	eval-rmse:7610.36401
[501]	eval-rmse:7605.39980
[502]	eval-rmse:7600.89259
[503]	eval-rmse:7596.38262
[504]	eval-rmse:7591.89117
[505]	eval-rmse:7587.21232
[506]	eval-rmse:7582.45802
[507]	eval-rmse:7577.96667
[508]	eval-rmse:7573.45186
[509]	eval-rmse:7568.83331
[510]	eval-rmse:7564.06250
[511]	eval-rmse:7559.57503
[512]	eval-rmse:7555.12840
[513]	eval-rmse:7550.52836
[514]	eval-rmse:7546.04175
[515]	eval-rmse:7541.32936
[516]	eval-rmse:7536.86510
[517]	eval-rmse:7532.25643
[518]	eval-rmse:7527.82269
[519]	eval-rmse:7523.10688
[520]	eval-rmse:7518.64717
[521]	eval-rmse:7514.08431
[522]	eval-rmse:7509.68315
[523]	eval-rmse:7505.25069
[524]	eval-rmse:7500.54455
[525]	eval-rmse:7496.00031
[526]	eval-rmse:7491.56780
[527]	eval-rmse:7487.18920
[528]	eval-rmse:7482.51439
[529]	eval-rmse:7477.94745
[530]	eval-rmse:7473.57464
[531]	eval-rmse:7469.20003
[532]	eval-rmse:7464.82237
[533]	eval-rmse:7460.00964
[534]	eval-rmse:7455.65464
[535]	eval-rmse:7451.26297
[536]	eval-rmse:7446.88911
[537]	eval-rmse:7442.40848
[538]	eval-rmse:7437.76585
[539]	eval-rmse:7433.42697
[540]	eval-rmse:7429.07093
[541]	eval-rmse:7424.61499
[542]	eval-rmse:7419.99099
[543]	eval-rmse:7415.66993
[544]	eval-rmse:7411.18550
[545]	eval-rmse:7406.83870
[546]	eval-rmse:7402.55159
[547]	eval-rmse:7397.94946
[548]	eval-rmse:7393.50479
[549]	eval-rmse:7389.20076
[550]	eval-rmse:7384.91732
[551]	eval-rmse:7380.33333
[552]	eval-rmse:7375.91330
[553]	eval-rmse:7371.64099
[554]	eval-rmse:7367.36864
[555]	eval-rmse:7362.80500
[556]	eval-rmse:7358.40289
[557]	eval-rmse:7354.13411
[558]	eval-rmse:7349.85847
[559]	eval-rmse:7345.60843
[560]	eval-rmse:7340.92240
[561]	eval-rmse:7336.67087
[562]	eval-rmse:7332.45388
[563]	eval-rmse:7328.22759
[564]	eval-rmse:7323.56015
[565]	eval-rmse:7319.32622
[566]	eval-rmse:7315.10700
[567]	eval-rmse:7310.91199
[568]	eval-rmse:7306.26278
[569]	eval-rmse:7302.04626
[570]	eval-rmse:7297.84418
[571]	eval-rmse:7293.61152
[572]	eval-rmse:7289.29480
[573]	eval-rmse:7284.83585
[574]	eval-rmse:7280.65727
[575]	eval-rmse:7276.44229
[576]	eval-rmse:7272.12361
[577]	eval-rmse:7267.68242
[578]	eval-rmse:7263.52090
[579]	eval-rmse:7259.33676
[580]	eval-rmse:7255.04176
[581]	eval-rmse:7250.85260
[582]	eval-rmse:7246.43317
[583]	eval-rmse:7242.28726
[584]	eval-rmse:7238.02356
[585]	eval-rmse:7233.85162
[586]	eval-rmse:7229.44939
[587]	eval-rmse:7225.32111
[588]	eval-rmse:7221.02141
[589]	eval-rmse:7216.89085
[590]	eval-rmse:7212.52227
[591]	eval-rmse:7208.41676
[592]	eval-rmse:7204.15816
[593]	eval-rmse:7200.05614
[594]	eval-rmse:7195.94713
[595]	eval-rmse:7191.55941
[596]	eval-rmse:7187.33453
[597]	eval-rmse:7183.20099
[598]	eval-rmse:7179.12239
[599]	eval-rmse:7174.78691
[600]	eval-rmse:7170.56305
[601]	eval-rmse:7166.49988
[602]	eval-rmse:7162.38756
[603]	eval-rmse:7158.05898
[604]	eval-rmse:7153.87634
[605]	eval-rmse:7149.83022
[606]	eval-rmse:7145.73493
[607]	eval-rmse:7141.54160
[608]	eval-rmse:7137.30045
[609]	eval-rmse:7133.26811
[610]	eval-rmse:7129.24289
[611]	eval-rmse:7125.08317
[612]	eval-rmse:7120.75595
[613]	eval-rmse:7116.72717
[614]	eval-rmse:7112.72648
[615]	eval-rmse:7108.56791
[616]	eval-rmse:7104.31031
[617]	eval-rmse:7100.26138
[618]	eval-rmse:7096.25350
[619]	eval-rmse:7092.13523
[620]	eval-rmse:7087.89482
[621]	eval-rmse:7083.89937
[622]	eval-rmse:7079.87132
[623]	eval-rmse:7075.76230
[624]	eval-rmse:7071.79253
[625]	eval-rmse:7067.56739
[626]	eval-rmse:7063.55571
[627]	eval-rmse:7059.44851
[628]	eval-rmse:7055.49800
[629]	eval-rmse:7051.29505
[630]	eval-rmse:7047.31348
[631]	eval-rmse:7043.22313
[632]	eval-rmse:7039.28346
[633]	eval-rmse:7035.08182
[634]	eval-rmse:7031.15594
[635]	eval-rmse:7027.05828
[636]	eval-rmse:7023.12528
[637]	eval-rmse:7018.95018
[638]	eval-rmse:7015.04055
[639]	eval-rmse:7010.98354
[640]	eval-rmse:7007.04299
[641]	eval-rmse:7002.86867
[642]	eval-rmse:6998.97036
[643]	eval-rmse:6994.94585
[644]	eval-rmse:6991.00858
[645]	eval-rmse:6987.12497
[646]	eval-rmse:6982.98761
[647]	eval-rmse:6978.97993
[648]	eval-rmse:6975.09576
[649]	eval-rmse:6971.17874
[650]	eval-rmse:6967.05253
[651]	eval-rmse:6963.05907
[652]	eval-rmse:6959.20668
[653]	eval-rmse:6955.30606
[654]	eval-rmse:6951.18624
[655]	eval-rmse:6947.20617
[656]	eval-rmse:6943.36736
[657]	eval-rmse:6939.27536
[658]	eval-rmse:6935.40727
[659]	eval-rmse:6931.43233
[660]	eval-rmse:6927.59668
[661]	eval-rmse:6923.79343
[662]	eval-rmse:6919.68170
[663]	eval-rmse:6915.72457
[664]	eval-rmse:6911.90894
[665]	eval-rmse:6908.09352
[666]	eval-rmse:6904.03332
[667]	eval-rmse:6900.08079
[668]	eval-rmse:6896.28050
[669]	eval-rmse:6892.22279
[670]	eval-rmse:6888.26785
[671]	eval-rmse:6884.46448
[672]	eval-rmse:6880.67681
[673]	eval-rmse:6876.63352
[674]	eval-rmse:6872.67947
[675]	eval-rmse:6868.93183
[676]	eval-rmse:6865.13563
[677]	eval-rmse:6861.10885
[678]	eval-rmse:6857.17171
[679]	eval-rmse:6853.43987
[680]	eval-rmse:6849.69667
[681]	eval-rmse:6845.66306
[682]	eval-rmse:6841.74599
[683]	eval-rmse:6838.01452
[684]	eval-rmse:6834.02790
[685]	eval-rmse:6830.22551
[686]	eval-rmse:6826.37523
[687]	eval-rmse:6822.65089
[688]	eval-rmse:6818.68569
[689]	eval-rmse:6814.92355
[690]	eval-rmse:6811.06476
[691]	eval-rmse:6807.35089
[692]	eval-rmse:6803.38630
[693]	eval-rmse:6799.65513
[694]	eval-rmse:6795.81236
[695]	eval-rmse:6791.85859
[696]	eval-rmse:6788.12381
[697]	eval-rmse:6784.44746
[698]	eval-rmse:6780.65997
[699]	eval-rmse:6776.69868
[700]	eval-rmse:6772.98386
[701]	eval-rmse:6769.32302
[702]	eval-rmse:6765.49266
[703]	eval-rmse:6761.54732
[704]	eval-rmse:6757.89806
[705]	eval-rmse:6754.25521
[706]	eval-rmse:6750.22167
[707]	eval-rmse:6746.53038
[708]	eval-rmse:6742.87201
[709]	eval-rmse:6739.23968
[710]	eval-rmse:6735.21863
[711]	eval-rmse:6731.54638
[712]	eval-rmse:6727.90305
[713]	eval-rmse:6724.23489
[714]	eval-rmse:6720.23973
[715]	eval-rmse:6716.63634
[716]	eval-rmse:6713.03286
[717]	eval-rmse:6709.14299
[718]	eval-rmse:6705.38153
[719]	eval-rmse:6701.75401
[720]	eval-rmse:6698.11251
[721]	eval-rmse:6694.27297
[722]	eval-rmse:6690.56507
[723]	eval-rmse:6686.99116
[724]	eval-rmse:6683.11805
[725]	eval-rmse:6679.49587
[726]	eval-rmse:6675.81402
[727]	eval-rmse:6672.19971
[728]	eval-rmse:6668.38160
[729]	eval-rmse:6664.89036
[730]	eval-rmse:6661.20155
[731]	eval-rmse:6657.61711
[732]	eval-rmse:6653.77519
[733]	eval-rmse:6650.08388
[734]	eval-rmse:6646.55914
[735]	eval-rmse:6642.73780
[736]	eval-rmse:6639.16168
[737]	eval-rmse:6635.48756
[738]	eval-rmse:6631.92470
[739]	eval-rmse:6628.11870
[740]	eval-rmse:6624.57103

### Results

In [30]:
y_true = np.array(y_test, dtype=float)
y_pred = np.array(model.predict(dtest), dtype=float)

In [31]:
print("R^2 Score: {:.4f}".format(r2_score(y_true, y_pred)))

R^2 Score: 0.2783